### ISSUE TITLE
Failed to perform the action switch/turn_on. invalid literal for int() with base 10: '15.0'

### ISSUE THREAD

**Issue by GraceO77** [petergridge/Irrigation-V5#100]
[V2024.12.01b2]

Issue was the same on previous version. Works a couple of times (random), but then does not run at all and cannot turn on any zone. 

Logger: homeassistant
Source: custom_components/irrigationprogram/zone.py:700
integration: Irrigation controller ([documentation](https://github.com/petergridge/irrigation-v5), [issues](https://github.com/petergridge/irrigation-v5/issues))
First occurred: 12:35:52 PM (2 occurrences)
Last logged: 12:36:54 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/irrigationprogram/zone.py", line 700, in async_turn_on_from_program
    if self.remaining_time.state <= 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by petergridge** [comment]
Hi, can you provide the diagnostics output for this. I can see what is happening but cannot determine why. 

I will have a fix release in the next 24hrs

**Comment by petergridge** [comment]
V2024.12.01b3 released

**Comment by GraceO77** [comment]
Thanks Peter, 
new version seems to improve, will allow zone to be turned on and off, but only once. then have to reload integration to get working again. 

PS - really appreciate the work on this integration. V12 looks very clever and really liking the autocreation on the helpers. 

Here is the log during the same period:

Traceback (most recent call last):
  File "/config/custom_components/irrigationprogram/program.py", line 555, in async_turn_on
    running_zones = await self.run_monitor_zones(running_zones, self._run_zones)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigationprogram/program.py", line 497, in run_monitor_zones
    await self.calculate_program_remaining(all_zones)
  File "/config/custom_components/irrigationprogram/program.py", line 427, in calculate_program_remaining
    self._program_remaining +=  int(zone.remaining_time.state)
                                ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '15.0'
2024-12-23 15:30:00.067 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/irrigationprogram/program.py", line 555, in async_turn_on
    running_zones = await self.run_monitor_zones(running_zones, self._run_zones)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigationprogram/program.py", line 497, in run_monitor_zones
    await self.calculate_program_remaining(all_zones)
  File "/config/custom_components/irrigationprogram/program.py", line 427, in calculate_program_remaining
    self._program_remaining +=  int(zone.remaining_time.state)
                                ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '15.0'

**Comment by petergridge** [comment]
Hi, It will be really helpful to get the diagnostic file, I can see what is happening but I cannot recreate the scenario locally.  I have 10 test zones in various states and they all run happily.

**Comment by petergridge** [comment]
Hi, b4 released, hopefully this one solves the problem for you.

I'm glad you like this release, it has been a work in progress for some time. But all the building blocks only came together for me only recently.

**Comment by GraceO77** [comment]
Looks like it has resolved. Really appreciate it and again well done on such a great integration!
