### ISSUE TITLE
Interleave Zone

### ISSUE THREAD

**Issue by Cook23** [petergridge/Irrigation-V5#14]
Hello,

I didn't find any way to interleave zone irrigation, I mean during waiting time of Z1, start Z2, during waiting time of Z2 if waiting time of Z1 is over restart Z1 if not start Z3 and so on.

The purpose is to limit the flow according to pump capacity. Let waiting time for soaking for each zone. Optimise watering time by running another zone when one zone is waiting for soaking.

Regards.

**Comment by petergridge** [comment]
Hi @Cook23 ,

This is not a feature I had considered. I can see issues with implementing this model. For example, where the watering time of one zone is longer than the wait time of the first zone will result in two zones running at the same time impacting the water pressure. 

I have not identified a method to ensure that zones to ensure that zones still run distinctly while limiting the complexity of the code to ensure it is maintainable long term. Currently the logic is geared toward running the zones/groups sequentially.

If water pressure is not an issue for you it is possible to have multiple zones running simultaneously using the grouping feature.

Thanks for providing the idea though, this type of input is it how this control got to where it is now.

Cheers
Pete

**Comment by Cook23** [comment]
Hello,

Thank you for this detailed answer. I was just revieing your code (end of switch.py) to see how it's done and how to modify to do this :)

Yes I have a problem with water pressure, thats the reason I can't run zone simultaneously.

For the point "watering time of one zone is longer than the wait time of the first zone will result in two zones running at the same time impacting the water pressure" there should be 2 way to manage that :

- Or it's the responsability of user to avoid this situation if he dont want 2 zones run simultaneously by setting sufficient wait time. 

- Or a zone can restart only if it's wait time is over AND no other zone is running (ie the setting "wating time" become in fact a "minimum waiting time" can be extended in real time to avoid conflict)

Regards,
Thierry.

**Comment by Cook23** [comment]
OK thanks.

**Comment by Cook23** [comment]
Hello, still no way to interleave zones?

**Comment by petergridge** [comment]
Hi, Still have not found a way to implement this without a heap of rework. A simple option may be to add the option to repeat the entire program a number of times. How long do you water and wait?

**Comment by Cook23** [comment]
Hello,

Actually I use "Simple scheduler" for watering but unfortunately schedule cannot be altered by automated rule. I need to change manually every month according to weather. With simple scheduler, schedule are completely free so it's the only way I found to do what I need. 

Watering schedule for my 6 area are :

10 min by hour repeated 2 times interleaved so total 2 hour for the 6 area

then

10 min every 20 min repeated 3, 6, 9, 12 times depending of season for 2 area against the 6 changing every day so 1 hour to 4 hour watering on cycle repeated every 3 days

all these area are interleaved. when one area stop another start. total duration can be 6 hour in summer.

Best Regards 


Le 3 sept. 2023 à 23:59, à 23:59, Peter ***@***.***> a écrit:

**Comment by petergridge** [comment]
`10 min by hour repeated 2 times interleaved so total 2 hour for the 6 area`
so this runs the areas in this order 1,2,3,4,5,6,1,2,3,4,5,6 for 10 minutes each time?

`10 min every 20 min repeated 3, 6, 9, 12 times depending of season for 2 area against the 6 changing every day so 1 hour to 4 hour watering on cycle repeated every 3 days`
Is this two additional zones or two of the 6 zones?
Running 1,2,1,2,1,2,1,2... between 3 & 12 times depending on the time of the year? 

So if I added a program repeat option that could be set via a sensor so it can be automated to change by season or weather this should satisfy your requirement.

Program 1: run each zone (1-6) for 10 minutes two times
Program 2: run each zone (1-2) for 10 minutes 3, 6, 9, 12 with the value provided by a sensor.

The start times cannot result in an overlap between the zones.

If you don't mind me asking where in the world are you?

**Comment by petergridge** [comment]
This is still not trivial to program as it impacts a lot of the timing aspects of the component. You can set this up as a 14 individual programs that are enabled based on the weather or season. A little more configuration but not complex to build

Program 1: area 1-6 at 6am
Program 2: area 1-6 at 7:00 am

Create 3 or 4 frequency automations to allocate to the groups of programs to vary the frequency from 3 to Off depending on the season/weather. I am not sure what rules you would like to implement.

Here is an example: 
Add the season sensor and use an template sensor like this to set the frequency. but you can use any other model to determine when to run. 
```
{% if is_state("sensor.season", ["summer","spring","autumn" ]) -%}
3
{% else -%}
Off
{% endif -%}
```
Frequency 1. Set to 3 or use a sensor (3 times)
Program 3: area 1-2 at 2pm
Program 4: area 1-2 at 2:20pm
Program 5: area 1-2 at 2:40pm

Frequency 2.  spring  (6 times)
Program 6: area 1-2 at 3:00pm
Program 7: area 1-2 at 3:20pm
Program 8: area 1-2 at 3:40pm

Frequency 3. autumn, spring (9 times)
Program 9: area 1-2 at 4:00pm
Program 10: area 1-2 at 4:20pm
Program 11: area 1-2 at 4:40pm

Frequency 4. summer, autumn, spring (12 times)
Program 12: area 1-2 at 5:00pm
Program 13: area 1-2 at 5:20pm
Program 14: area 1-2 at 5:40pm

You could use this in conjunction with the weather data to reduce watering if there has been rain, OpenWeatherMapHistory addon provides this.

**Comment by Cook23** [comment]
Hello, 

2 by 2 are for the same 6 zones. Only 6 zones total. 

I'm from south of France, Mediterranean climate. 2 weeks ago we have 42 oC and now it's 20 oC. 

Small water quantity every evening for all zone is to compensate evaporation of soil surface roasted durind day. As soil is roasted absorbtion of water is very poor during this phase. 10 min watering the wait 50 min absorbtion is nice. 

Long watering during night every 3 day is to provide water deep in the soil and avoid roots stay in surface attracted by surface humidity. 

The device I use to control the valve shut down automatically after 10 min. I can do nothing about it and, in fact, it's not bad to give time to absorb water and it's a safety in case of crash of home assistant. 



⁣Télécharger TypeApp pour Android ​

Le 4 sept. 2023 à 04:27, à 04:27, Peter ***@***.***> a écrit:

**Comment by petergridge** [comment]
What device do you use? I have added support for the Rainbird controller that has a similar issue and it can now water for longer than the default. If you let me know what type of controller you have I may be able to support it.

I will be in Lyon in a few weeks then heading for Dordogne and Bordeaux before heading north for Loire and Paris. A long way from Sydney but we love our holidays in Europe.

Our weather here can be quite similar.

**Comment by Cook23** [comment]
Hello,

 

This device :

 



 

https://fr.aliexpress.com/item/1005005579883033.html

 

According users forums, even flashing the firmware of main controller seems do not remove the 10 min limit.

 

The new model is this one :

 

https://fr.aliexpress.com/item/1005004329528467.html

 

I bought it but didn’t use yet.

 

September & beginning of October is one of the best time to visit south coast of France. Weather is nice. Sea is sometimes still warm (if wind come from south). Tourist are not there anymore.

 

My favorite place.

 



 

https://www.google.com/search?q=dramont <https://www.google.com/search?q=dramont&tbm=isch> &tbm=isch

 

By the way my email is: ***@***.***

 

 

 

 

De : Peter ***@***.*** 
Envoyé : lundi 4 septembre 2023 09:01
À : petergridge/Irrigation-V5
Cc : Cook23; Mention
Objet : Re: [petergridge/Irrigation-V5] Interleave Zone (Issue #14)

 

What device do you use? I have added support for the Rainbird controller that has a similar issue and it can now water for longer than the default. If you let me know what type of controller you have I may be able to support it.

I will be in Lyon in a few weeks then heading for Dordogne and Bordeaux before heading north for Loire and Paris. A long way from Sydney but we love our holidays in Europe.

Our weather here can be quite similar.

**Comment by petergridge** [comment]
Looks beautiful, so much of France to see and so little time.

I am not a big fan of Tuya devices, I have a home built ESP device, has been running with no problems for a few years now, can control 16 devices but I have only attached 4 solid state relays to it to control the solenoids all runs off a 24vac power supply. The box I put it in and the power supply were the most expensive part.

There is not a lot I can do with this one, there are no services exposed to help.

**Comment by petergridge** [comment]
Hi

I have just release V5.4.0 Beta. This supports multiple start times check out the help for setting it up, https://github.com/petergridge/Irrigation-V5#start-time. This should make it a little more streamlined to achieve your requirement.

Cheers
Pete
