### ISSUE TITLE
Program don't start at the time

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#18]
Hi
I'm testing irrigation v5
When I want to check program, I change the start time to 1 or 2 minutes after now and the program don't start.
The program starts correctly when I click on RUN.

What is the procedure for the changing time. Do I need to restart HA ?

Thanks for your help

**Comment by petergridge** [comment]
Hi, I guess you have the frequency set using a numeric e.g. every 2 days. If the program has run successfully and you change the time it will still be calculating the number of hours until that frequency allows it to run again. i.e. it sill only completed 2 hours ago and your setting is to run every 24 hours.

You have two options:
1. change to days of the week for your testing
2. use the irrigationprogram.reset_runtime service to reset the last run time

**Comment by Loic691** [comment]
Thanks
Should I have to launch in manual before test ?
Here's an other test fails :
Frequency is set to 1 (every day)
Time is 21h30.
I set program to run at 21h35.
I  called the reset_runtime.
At 21h35 the progam hadn't been launched

**Comment by Loic691** [comment]
Hi again
Program working now
I forget to ceate the  time_date Pre-requisite ;-(

Is there a forum discussion to talk about evolution or reguires about this integration ?

**Comment by jschroeter** [comment]
I had exactly the same problem and missed the [time_date integration](https://github.com/petergridge/Irrigation-V5#pre-requisite). Not sure if it would be possible to display a error message in this case.
Anyway, thanks a lot for your great work, seems to work as expected now!

**Comment by petergridge** [comment]
Hi @jschroeter,
I will remove that dependency, I have been meaning to code that in for sometime now but it never got very high on my to do list, it worked even though I knew I could do better. Anyway the change will be in the next release.

**Comment by petergridge** [comment]
Release 5.2.6 (beta) has removed the dependency on time-date sensor. I would appreciate if you could install the beta and verify the release.

**Comment by jschroeter** [comment]
Thanks a lot, just tried it, works like expected without the time-date sensor 🥳
