### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Dielee** [petergridge/Irrigation-V5#19]
Hello, 

first, thanks for this great custom component! 
I have two questions: 

1.  Is it possible to add an mositure sensor to your integration ? I haven't found anything about this yet. This would be very helpful to calculate how much water is needed.
2. Is the component counting the amount of rain if I provide an rainsensor ? Or will it only skip the irrigation if there were some rain today ?

Thanks!

**Comment by petergridge** [comment]
Hi @Dielee ,

1. This program does not directly calculate watering requirements but supports [water adjustment ](https://github.com/petergridge/Irrigation-V5#watering-adjuster-feature).  Using this feature you can create your own sensor to adjust the the watering to your requirement. Also have a look at OpenWeatherMapHistory on HACS or [here](https://github.com/petergridge/openweathermaphistory)

2. The rain sensor is simply a binary sensor, so it will skip todays cycle if it is currently active. If you have a numeric frequency the program will try again the next day, if the frequency is specifying explicit days to run it will try again on the next nominated day.

**Comment by Dielee** [comment]
Okay, thanks for your Input!
