### ISSUE TITLE
Naming of Version 5 folder

### ISSUE THREAD

**Issue by rjbungay** [petergridge/Irrigation-V5#2]
Hi Peter
Happy New Year 
I have an issue with my HA installation and appear to have 2 copies of your repository for Version 5 off the irrigation program. It appears you have changed the name of the GitHub repository and used both "-" and "_" so there have been irrigation-V5 and irrigation _V5. 
I get the following error in the HA logs:-

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:466 
Integration: HACS (documentation, issues) 
First occurred: 08:03:17 (5 occurrences) 
Last logged: 08:36:25

<Integration petergridge/irrigation_V5> GitHub returned 404 for https://api.github.com/repos/petergridge/irrigation_V5

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:466 
Integration: HACS (documentation, issues) 
First occurred: 08:03:17 (5 occurrences) 
Last logged: 08:36:25

<Integration petergridge/irrigation_V5> GitHub returned 404 for https://api.github.com/repos/petergridge/irrigation_V5

In HACS itself I see 2 repositories but there is no option to remove the one that points to the "_" version. I've looked but can't find where HACS stores the list to manually remove it. 

![image](https://user-images.githubusercontent.com/72338572/210210027-ec740e7f-26ed-4c0e-a714-bca511fbf5be.png)

**Comment by petergridge** [comment]
You may need to remove both repositories and then re add the latest one. I renamed the repository to align with the naming convention for all the HACS integrations.
![image](https://user-images.githubusercontent.com/40281772/210216216-b31e54aa-31d8-4665-a18c-68a60fb439c5.png)

Let me know if this works and I will close this issue.

Cheers
Pete

**Comment by rjbungay** [comment]
Hi Peter
You can't remove it like that as the repository no longer exists, so you can never get to that screen, you just get an "unknown error" when you click on it to get to that page. 
Maybe, you could re-create the irrigation_V5 repository temporarily for thoose like me to enable deletion but with a big warning to others not to use it but load the irrigation-V5 repsoitory?

Regards Richard

**Comment by petergridge** [comment]
I know the issue now, I have made the _ repository public again, I had made it private.

**Comment by rjbungay** [comment]
Hi Peter

Thanks, that has enabled me to remove it.

Regards Richard
