### ISSUE TITLE
Water adjustment using moisture sensor

### ISSUE THREAD

**Issue by aherbjornsen** [petergridge/Irrigation-V5#20]
I have set up the integration for watering 5 pots on my balcony.

I'm using drip watering controlled by solenoids connected to an 8x relay connected to an ESP32 and this is working perfectly.

I have MiFlora moisture sensors in the pots, and have set up a watering adjustment sensors based on the readings from these sensors.

This works but I've noticed that when the moisture increases during a watering cycle (and the watering adjustment sensor is changed accordingly) the watering time will dynamically be reduced in the middle of the cycle. This is suboptimal from my way of thinking. 

I could probably work around it, but I would like a setup where the cycle time is fixed at start and not adjusted during the cycle. Is this possible?

**Comment by petergridge** [comment]
Hi @aherbjornsen 
You are right, this process does not make a lot of sense. I have a couple of small changes to apply and will include this in the next release, in a few weeks.

**Comment by petergridge** [comment]
Applied in Version 5.2.2
