### ISSUE TITLE
Run time defaults to switch device max

### ISSUE THREAD

**Issue by bsp9493** [petergridge/Irrigation-V5#23]
Hi… 

been using this for a few years now, has always worked great!

my sprinkler device is Orbit B-hyve (has worked flawlessly with your integration for the last 2 plus years).   It appears to have a default run time of 10 mins per zone when activated.  This never used to be a problem in the past.  I would set the zone runtime via your integration and all was good

with the new configuration, I find the at the switch is using the default runtime of the b-hyve device, so the max I can run a zone is 10 mins regardless ow what my runtimes are set for.

Not sure if this is in your integration or the b-hyve one, so I will start here

your help, and work on this is appreciated as always!

Dave

**Comment by petergridge** [comment]
Hi Dave,

I don't think it is this integration as the model works quite simply by sending a command to the switch to turn on and then after the count down has completed it sends a command to turn off. Just the basic service call provided by HA.

Try turning on the switch directly using HA, not this integration. If it has the same behaviour it will be the Orbit, if it does not turn off, it is most likely the integration

A work around for longer watering time in the interim will be to configure the wait/repeat option to run for 9 minutes many times. 

Pete

**Comment by petergridge** [comment]
Hi Dave,

One more question, does the zone time count down show more than 10 minutes?

**Comment by bsp9493** [comment]
Thanx Peter, that was my thought as well…Something must have changed in the Orbit integration that I missed.Yes, thought about using the wait time as an interim fix:)ThanxdOn May 18, 2023, at 5:07 PM, Peter ***@***.***> wrote:﻿
Hi Dave,
I don't think it is this integration as the model works quite simply by sending a command to the switch to turn on and then after the count down has completed it sends a command to turn off. Just the basic service call provided by HA.
Try turning on the switch directly using HA, not this integration. If it has the same behaviour it will be the Orbit, if it does not turn off, it is most likely the integration
A work around for longer watering time in the interim will be to configure the wait/repeat option to run for 9 minutes many times.
Pete

**Comment by bsp9493** [comment]
Yes, zone count down show proper times…But default of the switch seems to override at 10 and turns it offdOn May 18, 2023, at 5:10 PM, Peter ***@***.***> wrote:﻿
Hi Dave,
One more question, does the zone time count down show more than 10 minutes?

**Comment by petergridge** [comment]
Hi How are you going with this issue? I was thinking if you cannot resolve this I can look at adding device specific support. I had a quick look at the Orbit implementation and it has it's own service calls that can be used to turn it on with a specified run time with your help and if you are interested I can look at a solution.

**Comment by bsp9493** [comment]
Thanx for reachin out Peter…Weird that it just started this year, must of missed something in one of the b-hyve updates.Not a problem, just added another program to compensate… dOn May 23, 2023, at 6:13 PM, Peter ***@***.***> wrote:﻿
Hi How are you going with this issue? I was thinking if you cannot resolve this I can look at adding device specific support. I had a quick look at the Orbit implementation and it has it's own service calls that can be used to turn it on with a specified run time with your help and if you are interested I can look at a solution.
