### ISSUE TITLE
Support for Master pump

### ISSUE THREAD

**Issue by hossamnagy** [petergridge/Irrigation-V5#3]
Good day, 

My current irrigation setup  has a master selonoid that needs to be turned on before I can activate any of the zone selonoids. This is is done to avoid having the zone selonoids under continuous  pressure and  increase their life span.

For e.g. to activate zone 1,  I need to enable two switches in home assistant ( Master pump switch 
+  zone 1 pump switch). Similarly to activate zone 2 I should enable both master pump and zone 2 switches and  so on

Is there a way to support this setup in the irrigation component?
Thanks

**Comment by petergridge** [comment]
Hi @hossamnagy,

You can configure a pump in the zone settings. There is a small delay built in to keep the pump running  as zones transition so the pump is not turning off and on between zones.

![image](https://user-images.githubusercontent.com/40281772/211928267-c6577dc8-21bf-4c8c-821b-54955af7912d.png)

I have missed this in my documentation and will reflect the change. 

Cheers

**Comment by petergridge** [comment]
Read me documentation updated
