### ISSUE TITLE
Just a question about time based watering

### ISSUE THREAD

**Issue by giig982** [petergridge/Irrigation-V5#31]
Hi, first of all, great job with this component: I used to have a bunch of automations to enable and disable irrigation each day of the week, and I had to deduplicate them in order to have a double irrigation slot in a day. Now I'm able to schedule the irrigation without any hassle!

My question is: as I have a little balcony and not a big garden, is it possible to set the time based watering with seconds and not minutes? Or maybe to have a switch that permits you to choose between one and the other magnitude?

Thank you.

**Comment by petergridge** [comment]
Hi, I am not keen to move to seconds for the run time at this time as it is a quite fundamental change to the underlying code. I did not consider this need when building the solution. I will keep this in the backlog of work though, I may come up with a way to affect this change in the future.

You can add the adjuster feature as a workaround, set the value at 0.5 so 1 minute will be treated as 30 seconds, 0.75 will 45 seconds and .25 will be 15 seconds. The details are here: https://github.com/petergridge/Irrigation-V5#watering-adjuster-feature

Cheers
Pete
