### ISSUE TITLE
Question about starting zones one after the other

### ISSUE THREAD

**Issue by GobiRan** [petergridge/Irrigation-V5#35]
Dear Petergridge,

I hope this message finds you well. I'm currently facing a situation where I have 12 valves but insufficient water pressure to open all of them simultaneously. Because of this, I'm interested in initiating the zones individually, without having to input a specific time for each zone. Ideally, I would like to designate a start time for the first zone or program, and considering that each zone has a designated run time, have them operate consecutively. To achieve this, it seems necessary to group the zones together. However, based on my understanding, grouping the zones currently results in simultaneous operation, which isn't what I'm aiming for.

Could you kindly confirm if this functionality is available, or would I need to create a separate program for each zone? The latter approach tends to get confusing with multiple start times, and any adjustments to the programs could potentially lead to overlapping. Do you have any suggestions or ideas to address this challenge?

Thank you for your assistance.

Best regards,
Robert

**Comment by petergridge** [comment]
Hi Robert,

The default operation of the program is to run the zone sequentially, the simplest implementation will have a start time for the Program and the run time in minutes for each zone.

Check out this post on the forum for a little more detail on setting up.

https://community.home-assistant.io/t/irrigation-custom-component-with-custom-card/124370/245?u=petergridge

Pete

**Comment by GobiRan** [comment]
I understand, thank you very much. I hadn't seen that in the documentation. Do the zones then run in the order they are displayed in the program (from top to bottom)?

**Comment by petergridge** [comment]
Yes the programs run in the order displayed in the custom card, this should be the order they are added in the program configuration.
