### ISSUE TITLE
Manual running when frequency is off

### ISSUE THREAD

**Issue by marshes** [petergridge/Irrigation-V5#36]
Is there a way to have frequency of ‘Off’ ignored if I want to manually run a zone for the configured time?

**Comment by petergridge** [comment]
Hi @marshes,

If the frequency is 'Off' I have designed the program to not let the zone run, however if the program is disabled using the 'irrigation_on' option the program will not run but the zone can be started manually.

For me the 'Off' frequency was to prevent anyone accidentally starting the zone while it was being repaired or work was happening in the area of that zone.

I hope that helps, there are so many ways that people want to use this that I have to make a decision based on what works for my implementations 😄 

Cheers
Pete

**Comment by marshes** [comment]
Hey Pete,

Thanks for clarifying! Will try it out tomorrow morning. Appreciate the response and also the development. Of all the smart things throughout our home, it was connected irrigation that got my SO to install HA and her phone 😂. Your integration + card and a couple of cheap zigbee hose controllers has given me smart sprinklers.

-Matt

**Comment by petergridge** [comment]
That was part of the driver for me as well, make it simple and relevant and they will come 😄
