### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by jschroeter** [petergridge/Irrigation-V5#37]
Thanks a lot for improving this component, very good idea to integrate the card!

After updating to V5.3.3 and V5.3.4 I get this error and the program doesn't run anymore:
```
Logger: homeassistant.config_entries
Source: custom_components/irrigationprogram/__init__.py:134
Integration: Irrigation controller ([documentation](https://github.com/petergridge/irrigation-v5), [issues](https://github.com/petergridge/irrigation-v5/issues))
First occurred: 8:21:16 PM (1 occurrences)
Last logged: 8:21:16 PM

Error migrating entry Bewässerung for irrigationprogram
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 633, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigationprogram/__init__.py", line 134, in async_migrate_entry
    new.pop(ATTR_SHOW_CONFIG)
KeyError: 'show_config'
```

Any idea?

**Comment by petergridge** [comment]
Hi, Thanks for finding these issues, this one I thought I had fixed but...

I can't take credit for the deployment of the card as part of the control. I stumbled on it in another control, thought it was a great idea and 'borrowed' it. 

Anyway this should be fixed now, let me know if you have any further problem or close this issue.

**Comment by jschroeter** [comment]
Thanks, seems to be fixed now!
