### ISSUE TITLE
Program config not visible

### ISSUE THREAD

**Issue by GobiRan** [petergridge/Irrigation-V5#38]
Dear Peter,

I've noticed one small thing in the latest version (5.3.5). The program configuration is not displayed within the irrigation card, so, for example, it's no longer possible to define the program start time through the Irrigation Card. Only the zones are displayed and can be expanded individually. The zones work as expected!

![grafik](https://github.com/petergridge/Irrigation-V5/assets/55636451/36387e97-4e29-4298-8074-24d6118ad26f)

**Comment by petergridge** [comment]
Hi,  there is an option in the card config to show the program it should be ticked by default

**Comment by GobiRan** [comment]
Okay, I found it, sorry. I've now added the YAML entry:
show_program: (optional default true) false will result in the program information being omitted from the card
This was missing in my setup. Now it works perfectly! :)
