### ISSUE TITLE
Latency issue?

### ISSUE THREAD

**Issue by maxoss** [petergridge/Irrigation-V5#40]
I'm not sure if its related to this but if I manually run a zone the delay to on state and countdown is huge around 17sec. I thought it has something to do with my old switch but now I have new one and still have this issue. 
When I run the full program manually, the switch starts instantly.

_Originally posted by @maxoss in https://github.com/petergridge/Irrigation-V5/issues/22#issuecomment-1716044445_

**Comment by petergridge** [comment]
Hi,

Can you give me an overview of your configuration. Some screenshots of your configuration will help also the values of the helpers and sensors used in the program and zones.

Also can you run the service call to determine if the lag is in there. This will help me narrow down the problem.
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/399411d6-8f16-46f7-ae61-4a2f44bff0bd)

**Comment by maxoss** [comment]
Actually nothing fancy in the config.
With service call exactly same problem.

![Screenshot_20230914_232342_Home Assistant](https://github.com/petergridge/Irrigation-V5/assets/757822/7c0b2f37-dea5-439f-9360-d4f2239ce675)
![Screenshot_20230914_232407_Home Assistant](https://github.com/petergridge/Irrigation-V5/assets/757822/d4c9d0f6-0433-423e-833e-8e5d5d1c643a)

**Comment by petergridge** [comment]
if you try adding the following to your configuration, this should prevent the program from attempting to run the zones that are offline.

<html>
<body>


enable_zone | input_boolean | Optional | Disabling a zone, prevents it from running in either manual or scheduled executions, adding 'Off' or similar text value to the run_freq helper will have the same result
-- | -- | -- | --



</body>
</html>

**Comment by petergridge** [comment]
Can you also send me the status of the offline switches i.e a screenshot of the developer tools state section for a offline switch. The program is already trying to determine if a device is offline and ignoring it but I am not sure how your device is presenting.

**Comment by maxoss** [comment]
> if you try adding the following to your configuration, this should prevent the program from attempting to run the zones that are offline.
> 
> enable_zone	input_boolean	Optional	Disabling a zone, prevents it from running in either manual or scheduled executions, adding 'Off' or similar text value to the run_freq helper will have the same result

This doesn't work

![Screenshot_20230915_071515_Home Assistant](https://github.com/petergridge/Irrigation-V5/assets/757822/71160901-a2f9-4748-aeb5-53265f35dc07)

**Comment by maxoss** [comment]
I can confirm that when all 3 switches are online there is no delay. So there should be a bug when one switch  or more are offline

**Comment by petergridge** [comment]
Hi I have found the issue and am working on a resolution. Thanks for providing this information

**Comment by petergridge** [comment]
Hi Beta 5.4.0 is available on HACS that resolves this issue. Let me know how you go.

Cheers
Pete

**Comment by maxoss** [comment]
Tried 5.4.0. I removed the power on 2 of 3 zones so they are unavailable state. Now I don't get any response when I manually start zone 1. So I will not start at all

**Comment by petergridge** [comment]
Can you send me the errors from the log

Cheers
Pete

**Comment by maxoss** [comment]
I can't find any error in the log

**Comment by maxoss** [comment]
Found the issue. The program itself need to be enabled to run manually a zone.

**Comment by petergridge** [comment]
That's great, I was worried when it did not work could not think of what could cause it. Thanks for letting me know. I will close the issue now.

**Comment by maxoss** [comment]
But I'd like to start the zone without enabling the program. Is that possible?

**Comment by petergridge** [comment]
I can change the behaviour, I'm about to head off on Holidays so it will be a 6-8 weeks before I can make the change unless I get it done in the next few days.

The logic I will apply is:
If the Program is disabled and the Zone is enabled the zone will run if manually started,
If the Program is disabled and the Zone is disabled the zone will not run,
If the Program is disabled it can still be initiated manually to run all enabled zones.

Cheers
Pete

**Comment by petergridge** [comment]
Hi Version 5.4.1 has been released that applies these rules.


If the Program is disabled it can still be initiated manually to run all enabled zones.
* If the Program is disabled and the Zone is enabled the zone will run if manually started,
* If the Program is disabled and the Zone is disabled the zone will not run,

If the Zone is disabled it will/can not run until it is enabled.

Cheers
