### ISSUE TITLE
Next run unavailable

### ISSUE THREAD

**Issue by Deub31** [petergridge/Irrigation-V5#41]
Hi,

Since the new version when I restart HA all next run are 'Unavailable'
Any ideas ?
Thx

**Comment by petergridge** [comment]
Hi,

Can you provide me an overview of your configuration. Screenshots and values of the helpers and sensors referenced in the program and zones.

With the additional information hopefully I can reproduce your problem.

**Comment by petergridge** [comment]
Hi, I have released beta version 5.4.0, it is available in HACS if you enable the show beta option,

**Comment by petergridge** [comment]
closing as stale
