### ISSUE TITLE
 A zone does not turn on if it has "Pump switch entity"

### ISSUE THREAD

**Issue by PioSkot** [petergridge/Irrigation-V5#42]
A zone does not turn on if it has "Pump switch entity".

If the zone has entity pump in the settings, watering the zone will not turn on. The watering time is then displayed but there is no countdown.

If I manually turn on the pump before starting the program, the integration turns it off.

**Comment by petergridge** [comment]
Hi,

Can you provide:
1. the version of the control you are running
2. screenshots of your configuration
3. values for the helpers and sensors you have configured

That will help me recreate the issue you are facing.

Cheers

**Comment by PioSkot** [comment]
The version is the latest. The problem was the update.

![image](https://github.com/petergridge/Irrigation-V5/assets/94479156/1a1cd0c9-532d-4eed-8455-7dad5bf80a7c)
![image](https://github.com/petergridge/Irrigation-V5/assets/94479156/4ea72575-6407-4478-812b-08979257ab7c)

Program:
Woda 2 start – 19:30:00
Woda 2 częstotliwość – 1
Woda 2 – on
Woda 1 przesunięcie stref – 9.0

Zone:
Płot – off
Woda płot czas – 15.0
Zawór główny – off
Podlewanie współczynnik – 0.8
Czujnik deszczu – off
Woda 2 płot - on

**Comment by PioSkot** [comment]
![image](https://github.com/petergridge/Irrigation-V5/assets/94479156/c0a96b77-39fb-4c9f-8a71-91f8c9eeb8c6)

**Comment by petergridge** [comment]
Hi, If you have not installed the beta version 5.4.0 can you try this.

Also I have one user report unusual behaviour after the upgrade but this was resolved after a restart of HA.

The other method to identify the problem cause is to remove all the configuration except the essential settings to allow it to run, so temporarily remove the interzone delay, adjustment... to determine if it is one of these that are impacting the operation.

I have tried to reproduce this with similar configuration as yours with 2 zones and a 15 minute runtimes with no issues
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/b970d833-1122-402d-81f0-6787fa019c3b)

**Comment by PioSkot** [comment]
No, that didn't help. 
I deleted all the configuration and did it again. 
Works. I close and thank you.
