### ISSUE TITLE
Question about water_adjustment

### ISSUE THREAD

**Issue by jmlt** [petergridge/Irrigation-V5#43]
Hello.
water_adjustment feature sensor should be defined as "runtime ajustment entity" on the zones configuration right?

Thank you.

**Comment by petergridge** [comment]
Yes that is correct, I will adjust the documentation so both options match.

**Comment by jmlt** [comment]
> Yes that is correct, I will adjust the documentation so both options match.

thank you! 
Also big thanks for this project in general, easiest way to get sonoff 4ch pro r3 working smoothly with stock firmware with easy lovelace support.

**Comment by Loic691** [comment]
Hi  @petergridge 
For water adjustment, what is your template code from OpenWeatherMapHistory ?
There's is 2 examples on the githhub page for 10mm of rain.
Is these 10mm for each complete cycle ? or for each day ?

For grass I read the amount of water needed is about 30 or 40mm weekly. Excact ?
So it's around 5mm daily and so on 15mm each 3 days.

Can you explain their example. I'm not sure to understand properly :
`{{ 
  [(10 
  - day0rain 
  - day1rain*0.5
  - day2rain*0.25
  - forecast1rain*forecast1pop*0.5
  - forecast2rain*forecast2pop*0.25)/10
  ,0]|max
}}`

**Comment by petergridge** [comment]
Hi, the factor is arbitrary, the 10mm works for me, as it just reduces the watering it does not cut stop it.

There is no particular science behind this, my advice would be to try this as it is and adjust the mm if it is to much or to little.

**Comment by Loic691** [comment]
Ok understood
