### ISSUE TITLE
Disabled status for toggles after a HA restart

### ISSUE THREAD

**Issue by bigmoby** [petergridge/Irrigation-V5#44]
Hi @petergridge ,
first of all, thank you so much for this great component! I really appreciate it! 🙏
I have a problem regarding the binary_sensor's status recovered after a HA restart. In other words, both binary_sensors (program config and program relay config) created by the integration through the input_boolean "enable configuration" and "enable program", are initialized to the False value after a restart...even if the related input_booleans are True.

I have attached some screenshots if they could help you to understand better:

<img width="1354" alt="Screenshot 2023-10-11 at 10 45 01" src="https://github.com/petergridge/Irrigation-V5/assets/11453002/a6ae6482-bf3d-4686-8f94-cf387d58dad7">

<img width="1353" alt="Screenshot 2023-10-11 at 10 44 53" src="https://github.com/petergridge/Irrigation-V5/assets/11453002/79bec197-4c47-408b-ad4f-2f53eddeba51">

<img width="1272" alt="Screenshot 2023-10-11 at 10 46 00" src="https://github.com/petergridge/Irrigation-V5/assets/11453002/de055f31-36b1-43d3-bfd5-b10af38830f4">

<img width="1293" alt="Screenshot 2023-10-11 at 17 04 15" src="https://github.com/petergridge/Irrigation-V5/assets/11453002/c85eb847-acca-46dc-955f-c59e01711351">

<img width="451" alt="Screenshot 2023-10-11 at 17 20 53" src="https://github.com/petergridge/Irrigation-V5/assets/11453002/b335cf97-6827-4631-83ce-81dfb63f7d92">

So, after a HA restart, I've to re-enable the four toggles (two for each program).
Please if you could help me.
Thanks a lot,
Fabio

**Comment by petergridge** [comment]
Hi,

I have checked my documentation and removed the redundant instructions.

In 5.3 onward the **show config** and **status** sensors are automatically created:

- **show_config** *binary sensors* are reset to off, these just determine if the configuration is visible in the custom card and do not affect the running of the program itself. I decided that it would be nicer to start the card minimised but I can add a call to get the previous state to the program in a future release.
- **status** *sensors* are also reset to 'off' as on restart all zones should be off and the program sends commands to turn off any running zones on a restart.

The only input_boolean you should need to create is to enable/disable the program or zone. These should retain their state between starts as default functionality in HA. I have created all my **helpers** from the **devices and services** UI they are behaving as expected.

**Comment by bigmoby** [comment]
Thanks a lot, @petergridge 🙌 I'll provide to delete the unuseful/deprecated config and I'll try to configure the program.
Thanks,
Fabio
