### ISSUE TITLE
Incorrect frequency calculations

### ISSUE THREAD

**Issue by filski** [petergridge/Irrigation-V5#46]
Hi,

The frequency calculation doesn't seem to work properly with integer values. See screenshot attached. It correctly picks up that it ran yesterday, but wants to run again today regardless of integer. Selecting a specific day value is ok. 

I can send any other details if they're useful. It displayed ok right after watering, but looking at it the next day shows this. 

Home assistant has been restarted since the watering ran, not sure if that is a factor. I can try to check if that is related.

Thanks,
Philip

![Screenshot_20231020_135508_Home Assistant](https://github.com/petergridge/Irrigation-V5/assets/25625321/25734d34-b24d-4e67-b2bc-e9254d3475bc)
![Screenshot_20231020_135736_Home Assistant](https://github.com/petergridge/Irrigation-V5/assets/25625321/ea565f7e-797e-4892-9e17-48d58dedba96)
![Screenshot_20231020_135743_Home Assistant](https://github.com/petergridge/Irrigation-V5/assets/25625321/18113981-eae2-427d-92d1-dc8e17c9e387)

**Comment by petergridge** [comment]
Hi,  I'm on holiday at the moment and won't be able to follow this up for another 3 weeks

**Comment by petergridge** [comment]
Hi, I have been having problems with numeric frequency, the logic should be simple but...., I think the current Beta is OK from my testing, what version have you installed?

**Comment by filski** [comment]
Sorry, missed the comment. Latest released version, 5.4.2 I think it is. Still reproducible, have just switched to specific days for now.

**Comment by petergridge** [comment]
Hi, I'm pretty sure 5.4.9 has this fixed now. I will close this issue off. please raise a new issue if this persists.
