### ISSUE TITLE
Card showing config cog but doesn't open - was ok / then not ok

### ISSUE THREAD

**Issue by Master-Atreides** [petergridge/Irrigation-V5#48]
Hiya,

Had an earlier version of the IrrigationProgram Custom Component card that was showing the config cog but wouldn't open the configuration panel... However I updated the IP Custom Component to V5.4.2 and it seemed to fix it / everything seemed to be working fine (all elements showing)... That is until last week when for no reason (haven't touched the integration since), the config cog on the card isn't working again (won't open the config panel) per this screenshot below. I've uninstalled and setup the integration (V5.4.2) from scratch again, however I get the same issue...

![Screenshot 2023-10-22 110754](https://github.com/petergridge/Irrigation-V5/assets/129144391/9292b91a-bc17-400c-9b3b-b6c786bfc1dc)

![Screenshot 2023-10-22 111043](https://github.com/petergridge/Irrigation-V5/assets/129144391/502ea7bb-879a-44f6-8f98-e36838c710da)

It was working fine before, showing start time, enable timer, next run, last run, frequency, duration, etc. - now i don't get anything (even if i reinstall the integration from scratch) and applying the standard card YAML below...

![Screenshot 2023-10-22 111731](https://github.com/petergridge/Irrigation-V5/assets/129144391/20b1c79f-692b-4ed1-ae86-10e8dd7028e6)

If it helps any, here's a list of the entities created by the integration for the Back Lawn Program...

![Screenshot 2023-10-22 112654](https://github.com/petergridge/Irrigation-V5/assets/129144391/10ee42bf-3dce-45d5-abde-39769f71e284)

I'm sure i'm just doing something dumb on my end... Let me know if you need any more info.

Kindly.

**Comment by petergridge** [comment]
Hi,  I'm on holiday at the moment and won't be able to follow this up for another 3 weeks

**Comment by Master-Atreides** [comment]
Not a problem Peter. Just thought I'd log it for your return and should anyone else be experiencing the same issue.

Kind regards.

Sent on the go with Vodafone
Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by filski** [comment]
Did you uninstall the separate front-end card? It's been replaced with an integrated card. I had the same problem and that seemed to help, along with a restart.

**Comment by Master-Atreides** [comment]
One thing that seems odd to me is that the Program data screen (in the Integration) no longer shows the 'Show configuration entity' field any more, i.e. I'm no longer able to select a 'Display Config' toggle (helper) like I was able to previously... unsure if this is the issue or not... Just in case - here's a screenshot of my Program data screen (missing the 'Show configuration entity' field).
![Screenshot 2023-10-27 185231](https://github.com/petergridge/Irrigation-V5/assets/129144391/ddb29e34-873f-4322-8c1a-03995d7ff454)

**Comment by petergridge** [comment]
Hi,

You no longer need to define the display config option this is automatically created for the program and each zone now.

Can you ensure that the old card is no longer installed check the resources definitions, you should only have one for the irrigation card: /irrigationprogram/irrigation-card.js?v=5.4.4
