### ISSUE TITLE
Unable to configure in integration entries

### ISSUE THREAD

**Issue by munit85** [petergridge/Irrigation-V5#49]
Hi, noticed this problem recently.  when i go to integration entries and click configure on my already configured setup i get the following error: 
![Screenshot 2023-11-03 083924](https://github.com/petergridge/Irrigation-V5/assets/49924807/22f5d31f-2ff7-41c4-b0c2-aea297819eed)

I was able to add entry and do a new configuration as a test, but once its applied and I try to "configure" it i get the same error.  The programs still seem to be running fine.

Anyway, I know you're on vacation, no rush. Just wanted to put it out there.

thank you

**Comment by GraceO77** [comment]
Seeing the same issue. Uninstalled, restarted and reinstalled. Still same issue persists

**Comment by petergridge** [comment]
Hi, I am having the same issue when running  on my deployed version but can not recreate the issue on my development environment. Puzzling but I will continue to investigate.

Cheers
Pete

**Comment by GraceO77** [comment]
Thanks Pete, anything we can do to help?

**Comment by petergridge** [comment]
I'll let you know if there is anything, at the moment I am playing to recreate it in the dev environment, I think I have a lead on it now.

**Comment by petergridge** [comment]
Odd, the options flow handler appears to have changed where the initial step is now different, it now aligns with the config flow. I will put a new version (beta) up soon, hopefully today, I will let you know so you can test it.

**Comment by petergridge** [comment]
I have published V5.4.5 that should address the configuration issue. There is a change that introduced in V2023.11 that impacted the options_flow process.

**Comment by GraceO77** [comment]
Just updated to V5.4.5 and the issue seems to be fully resolved. Thanks Pete, much appreciated.

**Comment by petergridge** [comment]
Thanks, unfortunately there is another bug that is causing problems so I will have another Beta out shortly. I will close this issue off.

Cheers
Pete

**Comment by petergridge** [comment]
V5.4.6 is out now, hopefully this puts this back to stable, I don't have much on the backlog now and want to let it settle for the holiday season and the Aussie summer.
