### ISSUE TITLE
config flow error

### ISSUE THREAD

**Issue by icygame** [petergridge/Irrigation-V5#50]
Super useful integration...I have one issue however: It is not possible for me to edit a program created in config flow. The error

> Config flow could not be loaded: {"message":"Handler does not support user"}

is returned when hitting the 'configuration' button on the integration page.

 I can delete and recreate a new program without issue, it is just not possible to edit. I'm not sure if this relates to my setup somehow or is a bug. 

Running Irrigation version 5.4.2 and HA 
Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2

**Comment by petergridge** [comment]
Hi, If you install the beta version this is fixed, I will be moving this to the main version in a week.

![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/953a621b-7e24-4739-8d7b-48ee33c7c59b)

Cheers
Pete

**Comment by icygame** [comment]
thx!!
