### ISSUE TITLE
Amount of rain from weatherstation => skip program

### ISSUE THREAD

**Issue by jellyneck84** [petergridge/Irrigation-V5#51]
Hello @petergridge , 

this is not a bug, it's more a question or feature request. I want to skip the irrigation program when in the last 48h the amount of rain exceeds a specific value (let's say 15mm).

I have already a custom sensor which calculates the amount of rain of the last 48hrs. 
I thought about having a helper binary sensor which i then use for the rain sensor instead of the rain sensor itself.
![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/71cb83dc-fd46-459d-b643-5a0e7333997c)

I'm relative new on HA, how can i define a helper from type template binary sensor which is "true" when the amount of rain sensor  is > 15mm ? Or is there any other option in your integration to skip rain when the rain in 48hrs value exceeds 15mm

![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/7fdbb663-e218-4cc8-8f1d-f3f3653c5181)

**Comment by petergridge** [comment]
Hi @jellyneck84 ,

Try this feature https://github.com/petergridge/Irrigation-V5#watering-adjuster-feature. I use OpenWeatherMapHistory to look at the past and forecast weather to adjust the amount of water applied, for example if 7.5mm equivalent rainfall has been received in the last few days the watering system will only run for 50% of the nominated run time. The OWMH component is configurable so it can use the information exposed to support many models, even watering more if the temperature is expected to be high.

Cheers
Pete

**Comment by jellyneck84** [comment]
Hallo Peter. But then i still need a helper which is set by an automation and Container the value, for example 0.5.

Any idea how to Set this? Through an automation? Or just a template sensor with a trigger? Maybe you have an example for me.

**Comment by petergridge** [comment]
Here is a template example your can try. This sample will will run in the developer tools/template window.

{% set rain48 = 16 -%}
{% if rain48 > 15 -%}
True
{% else -%}
False
{% endif -%}

swap out the rain48 constant for your sensor to test with your system values. 

once you are happy with the results you can create the binary sensor using the UI
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/bc1558cc-c963-4f7f-b1c7-865f6b354132)

**Comment by jellyneck84** [comment]
Ok, this will just Set it to true, or false, bit not the reduction value, but should work similar. Will give it a try. Thx

**Comment by jellyneck84** [comment]
Another question, even if offtopic: what does "Support for rainbird Controller " means in release notes? Isnt the Controller irrelevant, because you need just define the Zone switch for opening the valve?

**Comment by petergridge** [comment]
The value reduction is provided by the OWMH so once it is configured you reference the sensor in the irrigation component.

The rainbird controller has a default run time of only a few minutes, to allow it to run for longer the rainbird API is required to be called.

**Comment by jellyneck84** [comment]
> The value reduction is provided by the OWMH so once it is configured you reference the sensor in the irrigation component.
> 
> The rainbird controller has a default run time of only a few minutes, to allow it to run for longer the rainbird API is required to be called.

You mean to keep the connection with the controller open? I am using rainbird esp-rzx with WiFi lnk Modul.... is thought with the rainbird Integration its just a local connection to the Controller triggering the Zone. 

![Screenshot_20240110_063617_Home Assistant.jpg](https://github.com/petergridge/Irrigation-V5/assets/68947111/d3f803a3-8195-49a3-8f15-98be24b257c0)

Controller is offline because of powered off.....

**Comment by petergridge** [comment]
I don't have a rainbird controller and developed this with a user that was having issues. I am not sure how effective it is. If you are not having issues with longer run times that is good.

**Comment by jellyneck84** [comment]
Hey Peter, as spring is coming i did more config with your irrigation
integration, i think i figured out the most, but i have a few questions you
maybe can answer (sorry for using the old issue).

Watering adjustment: Normally you apply a factor here 0.5, 1.0 or something
which then reduces the runtime.
Do i need to select the variable for watering adjustment in the zone
settings at "entity for runtime adjustment" or is this value automatically
used when defined?
And the next question, what is then the "entity for runtime adjustment", i
created a helper for the runtime adjustment...
[image: image.png]
I assume i should use either the factor or the runtime adjustment, or is
both the same?

Next question: Can i see in any kind of variable the calculated adjusted
runtime with the factor included?

Thanks for your work
Daniel

Am So., 18. Feb. 2024 um 00:27 Uhr schrieb Peter ***@***.***>:

**Comment by jellyneck84** [comment]
Ah yeah, and a 3rd question: Can i setup the irrigation card to show me always all details of the zone (toggle the settings button by default)
![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/e3239660-8b1f-4985-b091-202ee6484696)

**Comment by petergridge** [comment]
Hi,

I use openweathermaphistory (HACS) to calculate the factor applied, it is exposed as a sensor. It uses the weather history and forecast data to determine if the watering needs to be adjusted. https://github.com/petergridge/openweathermaphistory


You can use any sensor or numeric input for this setting.

The adjusted time is only presented when the program starts.

The details are not display be default.
