### ISSUE TITLE
Irrigation card showing an error after latest HA update

### ISSUE THREAD

**Issue by hossamnagy** [petergridge/Irrigation-V5#54]
![IMG_0235](https://github.com/petergridge/Irrigation-V5/assets/15700909/cc48170a-0642-407a-bada-d2e675307175)
The shown error message started to appear after the last update. I tried to redownload  integration but this  didn't help

**Comment by petergridge** [comment]
Hi, this is odd, I am on the latest  HA running on RPI 4 no issues.

A couple of checks:

1. Did you download the beta version 5.4.8? It is only a few week old. 
2. You are using the card deployed with the component not the stand alone version from HACS, I still have not removed this from  HACS ☹️ 
3. Can you check your log file for any errors relating to the component.

Also, this is akin to trying CTL-ALT-DEL, 😄  , but clearing the cache on your browser is a good debug step.

**Comment by hossamnagy** [comment]
Thanks for that. It turned out the entity name for the zones weren’t correct.
