### ISSUE TITLE
Master pump go off between zone

### ISSUE THREAD

**Issue by todely** [petergridge/Irrigation-V5#55]
Hello

First thanks for your work !

I have define 3 zone and i have 1 master pump, same pump is in each zone configuration but when zone 1 is finish pump go off before start again for zone 2 ?
I wanna keep pump on for all the program, perhaps i have miss something in configuration ?

Thanks
Best Regards,

**Comment by petergridge** [comment]
Hi, I have found the issue and fixed it, my transition between zones has grown to be greater than the delay I had built into the pump monitoring, I have increased the delay and fixed an issue with a delay turning on the pump for the first zone I found while testing.

Release 5.4.9 has the fix.

**Comment by todely** [comment]
Thanks for this quick fix !
