### ISSUE TITLE
Next runtime zeigt "gestern"

### ISSUE THREAD

**Issue by jellyneck84** [petergridge/Irrigation-V5#57]
Häufigkeit steht auf 3, next runtime zeigt aber gestern?!

![Screenshot_20240310_215215_Home Assistant.jpg](https://github.com/petergridge/Irrigation-V5/assets/68947111/029841cd-598f-4d8e-a8f5-7f9469d81056)

**Comment by petergridge** [comment]
Sorry, my German is very bad,  can you translate for me. 

Cheers Pete

**Comment by jellyneck84** [comment]
Sorry Pete,

The value for next runtime is wrong.
It Shows "yesterday" , which makes no sense. The schedule is set to run
every 3 days.

Peter ***@***.***> schrieb am Mo., 11. März 2024, 01:15:

**Comment by petergridge** [comment]
Ok thanks, I thought that this issue was fixed,  I will look into it,  I am getting inconsistent results. 

What hardware are you using? Raspberry pi?

**Comment by petergridge** [comment]
Has the train sensor been active? This was the mode where the next run was not recalculated when the zone was not run.

**Comment by jellyneck84** [comment]
@petergridge I'm using a rasperry pi, yes. 
What do you mean with "train sensor" ? Or do you mean rain sensor?
It seems the time is correct, when the next run is on the same day, because this morning the time was then displayed correctly "Next run: in 9 hours". But yesterday evening, as you can see in the screenshot, it showed "Next run: yesterday"

**Comment by petergridge** [comment]
Yes rain sensor,  auto correct 😀.

Are you on the latest version?

**Comment by jellyneck84** [comment]
Yes, i'm on latest
![image](https://github.com/petergridge/Irrigation-V5/assets/68947111/8a5537f5-deb4-4e0b-909a-943698ccc67b)

Rain sensor is selected, but it was not raining the last days.... it just rained 0,3 yesterday evening, not sure if this corrected then the "next runtime" or if it#s showing now correct because of it's the same day.

**Comment by petergridge** [comment]
The translation comes from HA for yesterday/tomorrow... I have had issues that I have struggled to resolve as they are not occurring in the development environment but pop up on the final hardware. One issue has been in the inconsistent handling of timezone when comparing dates, I thought I had that one fixed. I will review it again. Sometimes I can over complicate my code and it leads to issues, time to take a scalpel to my code again.

**Comment by petergridge** [comment]
I have found one case that makes the next runtime not update, if you have manually started a zone and the start time of the is during that run time the next run is not maintained for the zones that were not processed.
