### ISSUE TITLE
 [Features] - Add Interlock Option to schedule programs

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#58]
At now, interlock is default true and no programs is run if they have the same start time.

If no difficulties, is it possible to add an option to schedule programs, which have the same start time, one after the other.
Or change default behavior to schedule instead of not run ?

**Comment by petergridge** [comment]
I'm not sure what you are trying to achieve.

Have you tried putting zones on different schedules and making a single program? For example the program can have a default frequency of 3 days, but zone 1 can be an exception and have it's own frequency of 1 day. Then you don't need two programs starting at the same time. The zones that are to run will run sequentially and those that do not need to run are ignored.

The interlock function was designed for larger installations that have pumps and want to run several pumps irrigating different areas.

**Comment by Loic691** [comment]
I have an automation which set starting time to sunrise each program
Each program (flower and grass) have differents parameters and different zones
I prefer keep this mode beacause I can launch individually grass and flower.

So a workaround is to set grass to sunrise - 1h and flower to sunrise + 1h
