### ISSUE TITLE
Timer Counts Down Quickly

### ISSUE THREAD

**Issue by freemchr** [petergridge/Irrigation-V5#60]
Great add on thank you! Really appreciated 

however I setup today as per instructions and noticed that if I start a manual start of 30 mins in length it starts counting down from 30, then in a minute ends up at 7 mins, then 3 mins or so then stops. 

Any ideas? Thanks again.

**Comment by petergridge** [comment]
Hi can you send me you configuration settings.

Also the HA version and app version you are running.

Cheers
Pete

**Comment by freemchr** [comment]
2024.3.1 
And latest from HACS
Was only installed tonight 
Configs are same as the tutorial. 

Is there a way I can send this to you?

**Comment by petergridge** [comment]
A screenshot will be fine

**Comment by petergridge** [comment]
One thing to verify is if you are using sensor inputs to any of the configuration components they are not changing during the watering time, this could impact the runtime.

**Comment by freemchr** [comment]
<img width="558" alt="Screenshot 2024-03-23 at 11 58 29 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/112f5d1e-60f7-467d-b644-ad8285c689bd">
<img width="542" alt="Screenshot 2024-03-23 at 11 58 16 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/8556a46e-1e23-454d-adab-548602a7f47a">
<img width="558" alt="Screenshot 2024-03-23 at 11 58 05 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/3a42dde1-086c-4a33-82ed-92b7329882c8">
<img width="368" alt="Screenshot 2024-03-23 at 11 57 39 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/456f0090-71a8-4467-ab18-138b6aa33d6d">
<img width="380" alt="Screenshot 2024-03-23 at 11 57 19 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/f340b075-8309-4d94-b7a2-339ce43a012c">
<img width="383" alt="Screenshot 2024-03-23 at 11 56 56 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/e2cf8c70-e5f8-48e7-b91a-04ecff06ad4e">
<img width="389" alt="Screenshot 2024-03-23 at 11 54 58 am" src="https://github.com/petergridge/Irrigation-V5/assets/157944269/02e29f9e-5ef0-424f-b749-2631673de32b">

These are all the settings.

**Comment by freemchr** [comment]
The flow sensor entity is just how much water has been used eg 1L or 3L through the timer.

**Comment by petergridge** [comment]
Flow sensor is litres per minute, when you use the flow sensor the watering 'time' becomes watering 'litres'. So the higher the flow rate the shorter the remaining time.

**Comment by freemchr** [comment]
Makes sense that fixed it thank you. 

What settings do you recommend to detect that if rain In area don’t water?

**Comment by petergridge** [comment]
Check out openweathermaphistory,  on hacs. 

This one looks at history and forecast rainfall to create an adjustment to watering, if you had a little rain it waters less if you have al Iot it stops the watering.
