### ISSUE TITLE
Config desactived

### ISSUE THREAD

**Issue by cgarret06** [petergridge/Irrigation-V5#62]
Good morning
thank you for this program.
I have a small problem, the installation went well but for 2 days I have had the config on the card which is deactivated.
thanks for your help @
![Screenshot_2024-04-09-08-07-56-438_io homeassistant companion android](https://github.com/petergridge/Irrigation-V5/assets/143909740/b7d49d7b-1879-4354-8bbd-17135bcde5d3)

**Comment by petergridge** [comment]
Hi @cgarret06,

the program will show as disabled if you have the input boolean irrigation_on attribute set as off.
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/7fd9832c-b0f6-4b17-b157-1e8f3a2e887a)

the zone will show as disabled if you have the input boolean irrigation_on attribute set as off.
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/22103a78-657a-4dac-a66f-afd8fbad5383)

If you continue to have problems, please send me a screenshot of the configuration for the program and zones.

Cheers
Pete

**Comment by cgarret06** [comment]
Merci pour ce retour rapide
J'ai bien le imput_bolean activé
![image](https://github.com/petergridge/Irrigation-V5/assets/143909740/2a6c63e1-feaa-4c2c-9cb8-0f5034e29f65)
![image](https://github.com/petergridge/Irrigation-V5/assets/143909740/982cc0bb-b0f6-404a-9103-fd67d758cec7)
![image](https://github.com/petergridge/Irrigation-V5/assets/143909740/df8a4ad6-a713-4524-b821-55178a2c0bc3)
Merci de votre aide

**Comment by cgarret06** [comment]
![Capture d'écran 2024-04-09 161139](https://github.com/petergridge/Irrigation-V5/assets/143909740/796db884-c92c-4203-b0ce-3d26101eb7e7)

**Comment by petergridge** [comment]
Ok, 

Then it could be the frequency, the Frequency. 

https://github.com/petergridge/Irrigation-V5#run-days-and-run-frequency. if the Frequency is not one of the expected values it could have this effect.

**Comment by cgarret06** [comment]
Bonjour
J'ai supprimé les fréquences mais j'ai toujours le même problème.

**Comment by cgarret06** [comment]
Bonjour,
J:ai relancé l'installation de l'interface dans HACS et ça refonctionne.
Merci de votre aide

**Comment by petergridge** [comment]
Your Welcome 😄
