### ISSUE TITLE
No Lovelace card

### ISSUE THREAD

**Issue by bradkemper** [petergridge/Irrigation-V5#63]
I followed the instructions for installing and configuring the IrrigationProgram Custom Component via HACS. But it doesn't seem to have automatically created a custom card type. So I went to HACS front end, and added it there. It said it was the companion card for irrigation v5, and was called IrrigationProgram Custom Card, so that seemed right. But even after installing it and restarting HA, when I try to add it to my dashboard, there is no UI. Just YAML, a message that there is no visual editor, and an error saying I need to specify an irrigation program. I suppose I could figure out how to do everything via YAML, but I was really expecting a visual editor to make it easier. What went wrong? Are there some logs I should look at?

**Comment by bradkemper** [comment]
I've tried uninstalling the card in HACS, restarting, updating the program, restarting, and restarting again. But every time I try to add the card, there is no UI.

**Comment by petergridge** [comment]
Hi, I have published the latest version in HACS as a standalone, I haven't been maintaining this version as the auto version was working well. If this becomes a broader issue I will go back to have two separate installs. It does come with some benefits as I can look at adding translation files if the card is published the 'standard' way.

I did notice a hiccup in my dev environment but it went away when I synced with the latest source. 

Let me know if this fixes you issues.

Cheers
Pete

**Comment by petergridge** [comment]
Hi @tbgoose that is good information, I am not sure what, but I have had to refactor a few elements that are be changed by HA. I will try and get it working again, I have published the Card as a stand alone on HACS if required.

**Comment by petergridge** [comment]
Hi V5.4.15 should resolve this issue, to test I deleted the component and any references in Settings/Dashboards/resources and re installed it was successful for me. I modified the path to the resource to accurately reflect the installation.

Please let me know if this corrects the problem for you
