### ISSUE TITLE
calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5

### ISSUE THREAD

**Issue by Sdahl1234** [petergridge/Irrigation-V5#65]
Detected that custom integration 'irrigationprogram' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/irrigationprogram/switch.py, line 317: self._unsub_monitor_start_time = async_track_state_change(self.hass, self._start_time, self.update_next_run), please create a bug report at https://github.com/petergridge/irrigation-v5/issues

Thanks for this great integration.

**Comment by petergridge** [comment]
Hi, I have moved V5.4.13 from beta to the current release this fixes this issue.

Cheers
Pete
