### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by zanna1972** [petergridge/Irrigation-V5#66]
Hi, I've installed and tested your integration and it's very interesting, but I have found some bugs.

1.
For each zone I have configured the pump entity and it's ok... solenoid on and pump on... fantastic!
Then I decided to keep my pump always on, so I removed from each zone the pump entity, saved and applied.
I turn on the pump switch, but after few seconds it moves to off. I have disabled the program, but nothing was changed. I uninstalled your integration and now I can move mi pump on and it stays on.

2.
I have a water well, sometimes It became empty and I must no acrivate the pump and irrigation.
I have a sensor in the water well to detect if it's empty, and I used this as "Rain sensor" to prevent start, but I read that "Rain sensor" Is not taken into consideration in manual-mode.
Could you add a new configuration option to manage the water well?

Could you check these bugs? And tell me if there is a workaround? 
Many thanks,  and congratulations,  it's really a super useful integration.

**Comment by petergridge** [comment]
Hi @zanna1972 

I have moved V5.4.13 from beta to the current release this fixes part 1 of your issues.

Part 2 is a little more complex.  I can add a water source monitoring option but cannot think of a suitable workaround for this
I will build this expecting a binary sensor:
- When 'off' the program will not run
From a service call,
From a scheduled start or,
From a manual start
- When a program is running and the sensor changes to 'off'
The program will terminate after a short delay

Let me know if this is what you want

Cheers
Pete

**Comment by zanna1972** [comment]
Hi Pete, thanks for your answer.
Exact! The water source is a binary sensor.
When It changes front on to off:
- if irrigation is running, must stops as soon as possibile
- if irrigation is waiting to start, must skip to the next schedule.

Thank you Pete, really appreciated

Il lun 13 mag 2024, 09:03 Peter ***@***.***> ha scritto:

**Comment by petergridge** [comment]
I am testing the changes now, there is a 5 second delay in turning the pump off in line with the delay for the flow meter processing. Hopefully this is not going to cause any issues with the pump running dry. I will hopefully release a beta by the end of the week. I typically leave the Beta for 3-4 weeks, in case there are any latent bugs that I did not find.

**Comment by zanna1972** [comment]
Hi Pete, thank you very much.
The delay Is not a problem because I set the pump 1 Meter below the sensor.
When it changes its status, the pump is still submerged.
When released I will test the beta version, and in case of problems, I
write a feedback

Il lun 13 mag 2024, 13:16 Peter ***@***.***> ha scritto:

**Comment by petergridge** [comment]
Hi, I have release 5.4.15 Beta that has water source monitoring, thanks for helping with testing

**Comment by petergridge** [comment]
I prefer to have a consistent approach. Rain sensor on, it is raining. Water source on, there is water. Zone enabled, and so on.

**Comment by zanna1972** [comment]
You are tight.
Unfortunately my water well is off when full of water.
Could you tell me how can I invert values?


Il gio 16 mag 2024, 21:49 Peter ***@***.***> ha scritto:

**Comment by petergridge** [comment]
Hi, You can create a template binary_sensor helper.

"{{ is_state(binary_sensor.well,'off') }}"

**Comment by petergridge** [comment]
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/48377315-f196-4689-b8a4-718b88038382)
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/89910e36-71dd-4c76-be6f-5655928c46e5)
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/f3d386e6-7adc-4ae9-b5e4-8cd240a9132c)
