### ISSUE TITLE
Gardena 1197-20 Water distributor automatic

### ISSUE THREAD

**Issue by DEFAYArnaud** [petergridge/Irrigation-V5#70]
Hello, 

I would like to know if it is possible to use the Gardena 1197-20 Water distributor automatic ?

Thank you in advance for your reply.

**Comment by petergridge** [comment]
Hi,  if it exposes switch entities to home assistant or will work. If it requires specific service calls then I will need to do some extra work.

**Comment by DEFAYArnaud** [comment]
ok thanks
