### ISSUE TITLE
Support for watering multiple times a day

### ISSUE THREAD

**Issue by myk3y55** [petergridge/Irrigation-V5#72]
Hi! First of all, thank you so much for this integration! I have to water my plants 2 times a day (6am and 10pm) and i cannot figure out how to do that. However, this schedule will change when autumn comes around and requires only 1 watering a day. An option to select frequency/day (1, 2, 3 times a day) alongside the current frequency (every 2, 3 days, etc) would be a nice feature to have! If there is such an option already and i have missed it in the documentation, please let me know! Thanks!

**Comment by petergridge** [comment]
Start time
You can define the start time using two methods.

As an input_datetime
This supports selecting the start time
image

As an input_text
This allows you to input multiple start times for the program
Time format MUST be hh:mm:00, 24 hour time format with 00 as seconds e.g. 18:55:00
Each time MUST be seperated by a ','
Use this regex pattern to help ensure the correct time structure (([0-2][0-9]:[0-5][0-9]:00)(?:,|$)){1,10}
If no valid time is supplied the start time will be defaulted to 08:00:00
image

**Comment by myk3y55** [comment]
Thank you for the quick response! Will switch from input_datetime to input_text to set both start times.
