### ISSUE TITLE
Cannot delete old programs

### ISSUE THREAD

**Issue by danielss24** [petergridge/Irrigation-V5#75]
I have installed time ago this integration and seems to work well, but i cannot delete old programers and it is overlaping with new ones i want to create with same info. Any solve to this?

I have tried to disable (which barely works for me now) and delete > reload config or restart HA and they are back...

**Comment by petergridge** [comment]
Hi, have you recently upgraded from an older version? what was the version you upgraded from?

Do you have a program defined in YAML as well as in the Config Flow, if so you can delete the YAML version .

**Comment by danielss24** [comment]
Hi, i have 5.4.15 version. I dont know if I need to install it again. I have done the input_number, selects and frecuency by YAML and all config by UI. So, i dont know what i need to delete

**Comment by petergridge** [comment]
Hi, I have release V5.4.16, I have it currently set as a Beta and will make it the main release once a few early adopters have had a chance to use if for a few weeks.

I have added a few additional debug statements in, please turn debug on for this component we may get a hint of what is happening.
<img width="304" alt="image" src="https://github.com/user-attachments/assets/0b20de80-936d-4062-b2aa-6ae1cb01fc39">

There is also a service you can run that will list the current configuration out for the component:
<img width="494" alt="image" src="https://github.com/user-attachments/assets/ff4f3d75-44bc-45dc-ab34-36198c04fef0">

If you could run these and check the log file for the information I could try to debug this issue some more.

**Comment by bjdshp** [comment]
i'm trying to delete as well.  Making a bit of a mess trying to delete individual components.  Can't figure it out.

**Comment by petergridge** [comment]
I have found some time at last to look into this. Sorry I have been busy with my day job.

Just checking to delete the irrigation program you are going to the settings:
![image](https://github.com/user-attachments/assets/444d6427-878c-434e-80c6-2514ae89203d)
and deleting from here:
![image](https://github.com/user-attachments/assets/df9c7360-274a-4aaf-a307-4935c191953c)
This should delete anything created by the component.
The other helpers you created can all be deleted either from the YAML if that is how they were created or from the settings:
![image](https://github.com/user-attachments/assets/9da5d2c0-c219-46df-acb9-9c59cc4f58ca)

If you can take some screenshots of the process you are following and issue you are having so I can understand the issue better.

**Comment by lorenzing** [comment]
I have the same problem of @petergridge. I'm not able to delete the old program as he explain

**Comment by lorenzing** [comment]
> And if you uninstall the component do they come back?

I've tyed to uninstall the component but I cant uninstall it becuse I'm not able to remove the entity correctly:
- First step: 
![image](https://github.com/user-attachments/assets/f61e88b7-eeb7-4dd0-9a5d-ebbdad29a535)
- Second step: 
![image](https://github.com/user-attachments/assets/0b28a97f-3952-4f5a-933e-69acd5984583)
- Msg: 
![image](https://github.com/user-attachments/assets/4acbc9d9-b398-43b4-a994-f2771098c2dd)
If I click remove the integration was removed, but I think this is a wrong way 😅

**Comment by petergridge** [comment]
Good to know Home Assistant is cleaning up after me 😄 

I did have some issues a few versions back where the config was not being removed, that is I fixed now. Let me know if this cleans up the mess for you.

**Comment by danielss24** [comment]
> Hi, I have release V5.4.16, I have it currently set as a Beta and will make it the main release once a few early adopters have had a chance to use if for a few weeks.
> 
> I have added a few additional debug statements in, please turn debug on for this component we may get a hint of what is happening. <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/40281772/356853654-0b20de80-936d-4062-b2aa-6ae1cb01fc39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzMwNTgsIm5iZiI6MTcyNDIzMjc1OCwicGF0aCI6Ii80MDI4MTc3Mi8zNTY4NTM2NTQtMGIyMGRlODAtOTM2ZC00MDYyLWIyYWEtNmFlMWNiMDFmYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5MzIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMWM5MDI1MDA2ZDRiMmExY2ZmYTZhN2JhZTY1OWE1YWIzZjY1MzE5MjU4Y2Y5NjZmZjM1YmZmNzY1YjBkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWRYMHJ1VtcXlZDJofl1Anl1omddOETt_gJKv08kCFI">
> 
> There is also a service you can run that will list the current configuration out for the component: <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/40281772/356853594-ff4f3d75-44bc-45dc-ab34-36198c04fef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzMwNTgsIm5iZiI6MTcyNDIzMjc1OCwicGF0aCI6Ii80MDI4MTc3Mi8zNTY4NTM1OTQtZmY0ZjNkNzUtNDRiYy00NWRjLWFiMzQtMzYxOThjMDRmZWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5MzIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NTY5YzFmMDQ5MTUyZDg2OTgyYzA5NmM4MTQ2NmIyMTI0ZTg1MDhjZmQ5YjE3NzdiYWNhOGIwOTFlZjgxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PgbY93afrWlNwaNP-pLQRR_h9WQF1e9lFwrN4hInW-Q">
> 
> If you could run these and check the log file for the information I could try to debug this issue some more.

Hi, regarding this. I have already turn on debug mode and run the action to list configuration. But i cannot find the version u mentioned. Just doing it with 5.4.15.
Where can i find log files?

**Comment by petergridge** [comment]
If you can try the process that @lorenzing followed above this sounds like it will clear the old config out.

To get the beta release:
![image](https://github.com/user-attachments/assets/20865a80-2225-429a-95f8-41a0170d0d56)
then select the show beta versions
![image](https://github.com/user-attachments/assets/6f47e9f6-f730-4c4d-88f3-6ff4aa9f5953)

To see the log:
![image](https://github.com/user-attachments/assets/82a16ebe-a63a-4f77-b43c-abde42f34a90)
![image](https://github.com/user-attachments/assets/3a3a3254-1292-4a29-8275-a18affc8502d)
![image](https://github.com/user-attachments/assets/4a2153d3-9a79-436b-b393-09bdf19c743a)

**Comment by petergridge** [comment]
Hi, Good new,  I have identified the problem

**Comment by danielss24** [comment]
Nice! what was about? ping when u have a new release

**Comment by petergridge** [comment]
V2024.09.01 is up as a Beta, there has been a lot of change under the covers so please let me know if you experience issues.

**Comment by petergridge** [comment]
Hi @danielss24, did the change fix your issue? Let me know and I will close the ticket.
