### ISSUE TITLE
Zones are running concurrently and doesn't stop

### ISSUE THREAD

**Issue by aalllop** [petergridge/Irrigation-V5#77]
I have configured 2 zones. The 2 zones has configured 1 minute of running. When the program starts the 2 zones are turned on at same time and never stops. Is necessary to configure something to run zones one by one?

**Comment by petergridge** [comment]
Hi @aalllop,

You are correct the zones should run concurrently unless explicitly set up to run in a group.

Can you:
1. Provide the version you are running
2. Can you check the log for error messages when it runs.
3. Send me your config there is a service you can run that will output the config to the log file
![image](https://github.com/user-attachments/assets/9da03a59-7c90-4ac6-bc4d-9632068cc5ba)
![image](https://github.com/user-attachments/assets/803087ec-9e72-409c-a798-a5bfb19cc90a)

Cheers
Pete
