### ISSUE TITLE
async_forward_entry_setup 

### ISSUE THREAD

**Issue by tevaadarelsol** [petergridge/Irrigation-V5#78]
Detected code that calls async_forward_entry_setup for integration irrigationprogram with title: [...] during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

Detected code that calls async_forward_entry_setup for integration irrigationprogram with title: [...] during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by tevaadarelsol** [comment]
Detected that custom integration 'irrigationprogram' calls async_forward_entry_setup for integration, irrigationprogram with title: Riego patio and entry_id: 01J2E4HP2GHS1HYGNFTHJW3TFW, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/irrigationprogram/__init__.py, line 43: hass.async_create_task(, please create a bug report at https://github.com/petergridge/irrigation-v5/issues
Detected that custom integration 'irrigationprogram' calls async_forward_entry_setup for integration, irrigationprogram with title: Riego patio and entry_id: 01J2E4HP2GHS1HYGNFTHJW3TFW, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/irrigationprogram/__init__.py, line 48: hass.async_create_task(, please create a bug report at https://github.com/petergridge/irrigation-v5/issues
Detected that custom integration 'irrigationprogram' calls async_forward_entry_setup for integration, irrigationprogram with title: Riego patio and entry_id: 01J2E4HP2GHS1HYGNFTHJW3TFW, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/irrigationprogram/__init__.py, line 53: hass.async_create_task(, please create a bug report at https://github.com/petergridge/irrigation-v5/issues

**Comment by petergridge** [comment]
Hi @tevaadarelsol, this is fixed in the latest version currently available as a beta. I typically leave the beta version up for a while before making it the main

**Comment by tevaadarelsol** [comment]
Thank you so much, waiting then for the next stable release.
