### ISSUE TITLE
Question: how to change sequence of zones

### ISSUE THREAD

**Issue by paulius2k** [petergridge/Irrigation-V5#79]
Hi,

is there a way to change the sequence of zones in a program?  Or is the only way to delete and recreate zones in the needed sequence?

Thank you.

**Comment by petergridge** [comment]
HI @paulius2k,

Currently the only way to change the sequence is to delete and recreate the zones. I will look at this feature in a future release though.

Cheers
Pete

**Comment by petergridge** [comment]
I have included an update with the next release to support adding an order to the configuration to effectively change the run order.

**Comment by petergridge** [comment]
V2024.09.01 is up as a Beta, there has been a lot of change under the covers so please let me know if you experience issues.

**Comment by paulius2k** [comment]
How was this feature implemented? I do not see it in any of the configuration menus.

**Comment by petergridge** [comment]
You need to update the configuration on the zones to set the order.
![image](https://github.com/user-attachments/assets/170a4e4f-b8f6-433f-afb3-d255d8346feb)
It then does a bubble sort on startup to set the order

**Comment by petergridge** [comment]
The config stays in the same order, but when the programs run they will be in the new order. I can look at changing the order in the config flow in a future release. I am not sure what the impact will be on the config flow overall though.

**Comment by petergridge** [comment]
Hi @paulius2k,

I have managed to implement the reorder on the config flow, it is much better, thanks for pushing :)

Pete

**Comment by paulius2k** [comment]
Thank you - looks very good now! :)
