### ISSUE TITLE
Visual Issues

### ISSUE THREAD

**Issue by kikorr** [petergridge/Irrigation-V5#8]
Good morning,

I come from a previous version. I have created an irrigation configuration where I have filled in the fields Start time entity, Run freq entity, Enable irrigation entity, show conf entity.
I have created two zones, both filling the same fields, zone switch entity, water runtime entity, rain sensor entity, ignore rain sensor entity.

When I show the data in the card I see that in zone 1 the last ran field does not appear while in zone 2 it does appear. In addition it does not allow to change the name of the zones as formerly it was allowed through the yaml.

Should I delete all the old configuration, or is there something I am not configuring correctly?

![Captura de pantalla 2023-01-24 153411](https://user-images.githubusercontent.com/708794/214322797-ba7ba2e4-a0f0-4a30-8e97-54ae6f631dbb.jpg)

![Captura de pantalla 2023-01-24 153321](https://user-images.githubusercontent.com/708794/214322299-8430ff7f-e87b-42bf-bac6-10568042b143.jpg)
![Captura de pantalla 2023-01-24 153505](https://user-images.githubusercontent.com/708794/214322789-2d19ee3a-47da-4da7-a8aa-597d77009f1d.jpg)
![Captura de pantalla 2023-01-24 153434](https://user-images.githubusercontent.com/708794/214322795-e6850244-4394-4da3-ab61-47930236f0d5.jpg)

**Comment by petergridge** [comment]
hi @kikorr,

A couple of question to help me:
What version of the Custom Control & Custom Card have you installed, I think you may need to upgrade your card version.
can you also take a screen shot of the attributes for the program.

You can change the name of the program in the switch.program_name entity itself.
![image](https://user-images.githubusercontent.com/40281772/214430346-243e2500-8ce2-4edb-a8cd-089529e0dfb3.png)

**Comment by petergridge** [comment]
A quick question, would you be willing to provide a translation for the config flow?

**Comment by petergridge** [comment]
Hi @kikorr,

I have release version 5.2.0-beta, this provides significantly more capabilities on the card than the previous version. I recommend you update to this version for both the card and the control.

**Comment by kikorr** [comment]
Thanks, I'll look into it this weekend.

**Comment by petergridge** [comment]
Hi @kikorr,

How did you go with this? Is it OK to close off this issue?

Cheers
Pete

**Comment by petergridge** [comment]
Stale issue
