### ISSUE TITLE
card error (Can not read properties of undefined (reading 'attributes'))

### ISSUE THREAD

**Issue by L0bit0** [petergridge/Irrigation-V5#80]
Hi

NOTE: even issue looks on the card I feel it is not working since last integration update.

Issue:
- Card is giving an error:
![image](https://github.com/user-attachments/assets/20eda2c0-46fa-4979-bf1a-ee84e468bd32)
- Card is properly showed on ipad App :-)
        - iPad
                ![image](https://github.com/user-attachments/assets/1fb86beb-f1b7-423a-80ad-dc4bb2f2991c)
        - Web
                 ![image](https://github.com/user-attachments/assets/c3c1431d-02e3-4057-9f2f-baf3caab8d96)
- Irrigation schedule looks is still working fine
- When I try to edit the card i see this:
![image](https://github.com/user-attachments/assets/19d28ff4-de23-4069-b666-4080bf8e9d47)
    - yaml:
```
type: custom:irrigation-card
program: switch.riego_no
entities: []
show_program: true
next_run_label: Next Run
last_ran_label: Last Run
remaining_label: Remaining time
```
- I tried to manually edit and add the switches but still do not work:
![image](https://github.com/user-attachments/assets/b82ac8b5-03c0-46be-a4ee-69adee77311b)
```
type: custom:irrigation-card
program: switch.riego_no
entities:
  - switch.valvula_riego_1_switch
  - switch.valvula_riego_2_switch
show_program: true
next_run_label: Next Run
last_ran_label: Last Run
remaining_label: Remaining time
```

- I reconfigure the zones, but still failing
- I confirmed valves and switches works fine.

Thanks

**Comment by petergridge** [comment]
Hi @L0bit0 

What browser are you using?
Have you tried clearing the cache?
Can you try incognito mode.

Cheers
Pete

**Comment by L0bit0** [comment]
Browsers: chorme on mac, and fully kiosk
clearing cache: tested, same thing
incognito: tested, same issue...

**Comment by L0bit0** [comment]
BTW, i think it is duplicated with this: https://github.com/petergridge/Irrigation-V5/issues/81

feel free to merge

**Comment by L0bit0** [comment]
last update: now it is working fine :-)
![image](https://github.com/user-attachments/assets/5c560f3d-20b3-44ad-8979-a8428bdd28f4)
 I did not did anything... as far as i know...

i will keep monitoring during some days and see if issue come back...

**Comment by L0bit0** [comment]
in cas it helps i tried some chrome developer tools and see some components errors:
![image](https://github.com/user-attachments/assets/f42a7068-2055-448e-a516-c1cbf2b5febe)
![image](https://github.com/user-attachments/assets/89d3ca4d-250f-4eb3-83fb-1ee14bc96035)

this is the exported log: 
[homeassistant.local-1725445742586.log](https://github.com/user-attachments/files/16868807/homeassistant.local-1725445742586.log)

**Comment by petergridge** [comment]
That is good thanks:

Did you install the card from HACS? The card auto installs now and should be version 5.4.20

![image](https://github.com/user-attachments/assets/fef2283e-fa38-44ec-8d25-0f42b423937f)
![image](https://github.com/user-attachments/assets/186df976-fe8b-43cd-a823-e8e9db511fc9)

If you have the standalone instance installed if you remove that that should help.

**Comment by L0bit0** [comment]
I manually updated and looks good now.  I will wait a couple of days for 100% confirmation, but it looks good.

Thanks!!!
