### ISSUE TITLE
Card UI config does not work

### ISSUE THREAD

**Issue by paulius2k** [petergridge/Irrigation-V5#81]
Hi,
I see this error in my Irrigation card configuration:
"hass is not defined".
YAML configurator works ok.

I am using Chrome. Same error in incognito mode.

<img src="https://github.com/user-attachments/assets/8cdcb525-ca9c-4935-bb28-37518b9a000e" width=50%>

**Comment by Santos-m** [comment]
I have the same problem

**Comment by petergridge** [comment]
I know this is a big stick for the problem but can you try to uninstall the app and card if you have it installed separately from HACS and reinstall it. I just cannot recreate the issue at my end.

**Comment by paulius2k** [comment]
I have installed **everything** from HACS.

By uninstalling - do I loose the program/zone setups?

**Comment by paulius2k** [comment]
Yes, I installed card from HACS.
![image](https://github.com/user-attachments/assets/a52f727b-98f2-441e-a430-0e0f5d93d5a0)

**Comment by petergridge** [comment]
Do you have two instances of the card installed? 5.4.20 is installed automatically, if you have previously installed the card standalone from HACS this could be the issue the last stale version would have been 5.4.13 I think.

An yes if you uninstall you will ned to reconfigure but all your helpers will not be impacted

**Comment by paulius2k** [comment]
No, I have only once installed v5.4.20 from HACS, I have not installed any other versions before.

**Comment by petergridge** [comment]
You can try downloading and re installing the component, and restarting Home Assistant

**Comment by paulius2k** [comment]
Redownloaded. Same error.

Maybe it's not very important, as everything is in the YAML.
Should I close this issue?

**Comment by petergridge** [comment]
Hi All, I have identified the issue, a change to the way cards support visibility in the newer release of HA seems to have had an impact. I will add the change into the upcoming release.

**Comment by petergridge** [comment]
V2024.09.01 is up as a Beta, there has been a lot of change under the covers so please let me know if you experience issues.

**Comment by paulius2k** [comment]
Works ok now.
