### ISSUE TITLE
the programm is running every day and is ignoring the configured days

### ISSUE THREAD

**Issue by AlexanderTurnowsky** [petergridge/Irrigation-V5#83]
I have the latest version installed [V5.4.20] and HA 2024.8.3.
It's configured like you described it in https://github.com/petergridge/Irrigation-V5/blob/main/help/help.md.
It was working before the last version and HA 2024.7.4.
see screenshot, it says it will run tomorrow but was running today.
![image](https://github.com/user-attachments/assets/273b7ad7-f807-42af-9669-48962b91bc9d)
In the past i had for sure also the old addon installed with the "scheduler component".

Any suggestion how i can fix this?

**Comment by petergridge** [comment]
Hi, are you using an automation to set the start time? There has been an impact on the latest release where if the start time changes dynamically it can manifest with your problem.

**Comment by petergridge** [comment]
I can see the 'next run' is correctly set to 2 days, but I would expect the 'last ran' to be <24hrs.

Can you try a numeric frequency 3 or 4 to see if that performs as expected. I am testing the named days now. I typically use every 3 days in my implementation.

**Comment by AlexanderTurnowsky** [comment]
> Also, I have the same issue as described in #81

this is also on my side, maybe this has something to do with it.

**Comment by petergridge** [comment]
I have identified the issue here, unrelated to #81, a fix applied for another issue introduce this one. I still have a lot of testing before releasing it.

**Comment by Loic691** [comment]
Hi @petergridge 
This is the same for me.
We had discussion about this issue in another thread.
I done other tests and confirm the programs run everyday even with no change in startime.

**Comment by petergridge** [comment]
V2024.09.01 is up as a Beta, there has been a lot of change under the covers so please let me know if you experience issues.

**Comment by Loic691** [comment]
> V2024.09.01 is up as a Beta, there has been a lot of change under the covers so please let me know if you experience issues.

Updated.
Waiting next cycle tomorrow or after tomorrow and let you know

**Comment by Loic691** [comment]
Hi @petergridge 
For information
Yesterday Next cycle was panned in 3 days !
This morning irrigation cycle was not launching. It's a good news !
Have to wait 2 days to see if issue is solve
Thanks

**Comment by petergridge** [comment]
Good news, you can also provide a sensor directly to the component now.  The method is in the documentation

**Comment by Loic691** [comment]
> Good news, you can also provide a sensor directly to the component now. The method is in the documentation

Great for template sensor. I will wait to check the issue first and will change to template sensor instead of automation

For info in your doc

```
Start time
You can define the start time using two methods.
```
You have 3 methods ;-)

**Comment by Loic691** [comment]
I found a bug
A program was launched and I stoped it manually
Here's the capture of the next cycle => 3 minutes AGO
Next cycle must be a future date

![image](https://github.com/user-attachments/assets/ca996b08-e2ab-47fb-9f92-bd0a587abcd1)

**Comment by petergridge** [comment]
Hi V2024.09.04 has some significant changes that improve the card performance.

Would you like to help with some translation to French? If you can translate these it will provide a better experience.

```
	"off": "Off",
	"on": "On",
	"disabled": "Disabled",
	"pending": "Pending",
	"eco": "ECO",
	"program_disabled": "Program disabled",
	"controller_disabled": "Controller disabled",
	"unavailable": "Unavailable",
	"raining": "Raining",
	"adjusted_off": "Adjusted off",
	"no_water_source": "No water source detected"
```

**Comment by Loic691** [comment]
Oh Yeah

	"off": "Arrêt",
	"on": "Marche",
	"disabled": "Désactivé",
	"pending": "En attente",
	"eco": "ECO",
	"program_disabled": "Programme désactivé",
	"controller_disabled": "Contrôleur désactivé",
	"unavailable": "Indisponible",
	"raining": "Pluie",
	"adjusted_off": "Aucun ajustement",
	"no_water_source": "Source d'eau non détectée"

**Comment by petergridge** [comment]
Hi V2024.09.05 has been uploaded with the French translations.

I'll close this issue odd now. Just raise a new one if you find new issues.

**Comment by Loic691** [comment]
For the moment it seams OK but weather is rainy so I have to wait...
Don't try to stop a program.
Do you see my post here ?
https://github.com/petergridge/Irrigation-V5/issues/83#issuecomment-2354859985
Do you find anything wich can cause this ?
