### ISSUE TITLE
Scheduled zones becomes unavailable whenever the HA host reboots

### ISSUE THREAD

**Issue by soheiladeli** [petergridge/Irrigation-V5#84]
Hi, I have latest version HA OS (2024.9.1) running on a VM which has a reboot schedule for two times a week and I have the latest version of the irrigation program (V5.4.20).
I noticed whenever the HA host reboots the irrigation automation is not running as scheduled. 
I had a look next time and I noticed after the HA host reboots, the 'Next Run' time on the zone becomes unavailable an it does not run on the scheduled time.

<img width="373" alt="image" src="https://github.com/user-attachments/assets/f0657a04-01d9-4afc-a71a-5e8073dc3443">

If I make a dummy change on the program time, then it becomes available and shows the 'Next Run' time correctly as you see below.

<img width="372" alt="image" src="https://github.com/user-attachments/assets/c0df4421-84be-4789-9173-71694c9087ba">

For now as a temporarily solution I have set a automation to update the program time helper about half an hour after the HA host reboot time, which make it working.

**Comment by petergridge** [comment]
Hi @soheiladeli 

V2024.09.01 is up as a Beta, I have not been able to recreate you specific issue with this release. Please try this version and let me know if the issue persists.

Pete

**Comment by soheiladeli** [comment]
Hi @petergridge , thanks for looking into this. I just installed the new V2024.09.01. unfortunately its happening again after the reboot as you see below:

<img width="372" alt="image" src="https://github.com/user-attachments/assets/ebb86fc8-231a-4b4a-a806-15a065e81158">

 if I disable and then enable the program or the zone, then it shows the Next Run_

**Comment by soheiladeli** [comment]
mo, there are  no errors in the log!

**Comment by petergridge** [comment]
The next run goes into an unavailable state when the switch/valve does not have a valid on/off state. So I am guessing that the Irrigation program is checking these before they have completed setting up.

If you restart HA, not your entire VM does the same issue occur?

**Comment by petergridge** [comment]
Are you comfortable with modifying a little code?
at line 374 of the switch.py file:
change
        self._unsub_start = async_at_start(self.hass, hass_started)
to
        self._unsub_start = async_at_started(self.hass, hass_started)

This should wait for HA to complete the start before firing the next_run calculation. It may work, it does not impact the operation on my hardware.

**Comment by soheiladeli** [comment]
> The next run goes into an unavailable state when the switch/valve does not have a valid on/off state. So I am guessing that the Irrigation program is checking these before they have completed setting up.
> 
> If you restart HA, not your entire VM does the same issue occur?

just tested with only restarting HA, and it happened again

**Comment by soheiladeli** [comment]
> Are you comfortable with modifying a little code? at line 374 of the switch.py file: change self._unsub_start = async_at_start(self.hass, hass_started) to self._unsub_start = async_at_started(self.hass, hass_started)
> 
> This should wait for HA to complete the start before firing the next_run calculation. It may work, it does not impact the operation on my hardware.

Ok Thanks, I'll change the code and give it a try now

**Comment by petergridge** [comment]
Sorry, I forgot the import. At line 28:

from homeassistant.helpers.start import async_at_start

Add ',async_at_started'

**Comment by soheiladeli** [comment]
Updated the code and rebooted but unfortunately it still happens and the Next Run is unavailable

**Comment by petergridge** [comment]
Thanks,  I have a couple of ideas to progress this, I thought that solution was too easy, but worth a try

**Comment by petergridge** [comment]
Here is one more change to verify:

Can your replace the function check_switch_state(self): with the code below. Make sure to maintain the indentation.

This will wait for a few seconds before reporting a switch as unavailable.

irrigationzone.py line 476.

```
    def check_switch_state(self):
        """Check the solenoid state if turned off stop this instance."""
        for _ in range(CONST_LATENCY):
            if self.hass.states.get(self.switch).state in ["off","closed"]:
                return False
            if self.hass.states.get(self.switch).state in ["on","open"]:
                return True
            asyncio.sleep(1)
        return None
```

Hopefully this solves the problem.

Cheers
Pete

**Comment by soheiladeli** [comment]
After rechecking I noticed that the state of my water tap timer stays unknown for almost 30 seconds until it becomes available. Its strange, as it is a Zigbee device, all my other zigbee devices become available almost instantly but for some reason the state of this tap timer and also my soil sensor stay unknown for about 20-30 seconds. Anyway thank you for looking into this, I don't think this issue is related to your component, but wish there was a way for me to fix it.

**Comment by petergridge** [comment]
I haven't given up on this, I have added monitoring of the zones, when the state changes it should trigger to set the next run attributes. It does not appear to impact the process, but I may to remove it if the early adopter Beta downloaders find issues.

Let me know if it works, it is difficult to test.

**Comment by soheiladeli** [comment]
excellent job! tested and YES, its working now on the V2024.09.02

Thank you very much!

**Comment by petergridge** [comment]
happy to help, it is unlikely that you will be the only person having the issue, the zigbee devices are getting cheaper and more common. Hopefully no knock on effects. I'll close this ticket.
