### ISSUE TITLE
Change entities created by a program if program name is changed (enhancement request)

### ISSUE THREAD

**Issue by L0bit0** [petergridge/Irrigation-V5#86]
Hi

I did a typo on a program creation, I was able to rename, but I realize that entities created still have the orginal name.

I assume that if I manually rename it, the program will stop to work, so I prefer to delete the program and create a new one from the scratch.

I know it is not a critical enhancement, as all keep working fine, but it will help to keep things organized.

Thanks in advance

**Comment by petergridge** [comment]
Hi,  when you rename an entity it changes the'friendly name' but the underlying entities are unchanged. This is a HA feature.

If I name the items based on this it will be possible to have duplicate items as the friendly name does not need to be unique.

**Comment by petergridge** [comment]
Hi, you cannot change the Entity ID without impacting the operation of the component. You can change the Name (friendly name). The program needs to be specific in naming the entities so they can be referenced throughout the component. I am not looking to change this in any future release.
