### ISSUE TITLE
Irrigation starts wen Raining sensor is true

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#89]
Hi
On my 3 programs, two have been launched this morning instead not...
Raining Sensor is true since yesterday afternoon.

My version : last update 2024.09.06

Next cycle is yet to Rain, so OK with this information

![image](https://github.com/user-attachments/assets/09bf8e99-05dd-407f-9297-093a96c5ab44)

**Comment by petergridge** [comment]
Hi I spent days testing and still issues!

I found a problem with setting the last ran time. I will put out a new version shortly.

Then see what new issue you can find me!

**Comment by petergridge** [comment]
V2024.09.07 uploaded.

**Comment by Loic691** [comment]
Think it was good now but I have to test the stop cycle when irrigation is running.
Wait few days before closing the issue.

You can replace french traduction "Aucun ajustement" by "Seuil de pluie atteint"  => English trad is "rain threshold reached"

**Comment by Loic691** [comment]
Problem is not solved...
Program is launched even if the rain sensor is on

![image](https://github.com/user-attachments/assets/8d9a2b5c-5858-4db8-a9f3-31a055c55334)

**Comment by petergridge** [comment]
Hi I will keep looking, 
The standard rain sensor model is definitely working in my testing. I just can't find a method that gets your result. 
Is it possible your rain sensor changed after watering commenced?

**Comment by Loic691** [comment]
Hi
I noticed a strange thing on the rain sensor switch...

When i click on it I saw last triger is sensor.openweathermap_rain

But when I enter in the template of this sensor, i'm not using openweathermap_rain...
I just use my own forecast and amount of rain in the last 24h.

So an idea, do you have a hardcode rain sensor ?

**Comment by Loic691** [comment]
No it seams not be that...
In my template i have a sensor made with a simple tempate which extract attribute of weathermap rain sensor...
So HA seams showing the main sensor source instead  of the  intermediate sensor.

So i don't understand why irrigation program is launched if the rain sensor is true....

> Hi
> I noticed a strange thing on the rain sensor switch...
> 
> When i click on it I saw last change by sensor.openweathermap_rain
> 
> But when I enter in the template of this sensor, i'm not using openweathermap_rain...
> I just use my own forecast and amount of rain in the last 24h.
> 
> So an idea, do you have a hardcode rain sensor ?
> Maybe an issue of HA But I never seen that...

**Comment by TheRoarman** [comment]
I had the same yesterday (Monday). It was raining, and the HA sensor was "TRUE".
I quickly logged into HA and stopped the program.

My program is set to run on Mon, Thu. Then this morning (Tuesday), It started again while the rain sensor was also still set as TRUE.
and I am running V2024.09.07

My binary.sensor is a template based on the amount of rain fallen in the last two days. 
{% if states('sensor.rain_over_last_48hours') | float(0) > 0 %}
   True
{% else %}
   False
{% endif %}

I'm veyr busy at work at the moment, but if I get a chance, i'll play around a bit with a static/manual rain sensor.

**Comment by petergridge** [comment]
Finally found the problem, sorry it took so long. I will have a new release up shortly

**Comment by Loic691** [comment]
Nice job ;-)
For curiosity, what it is ?

**Comment by petergridge** [comment]
I was using the wrong state attribute. It now uses the state as stored in the status sensor created for each zone.

**Comment by petergridge** [comment]
V2024.10.01 published as draft.

**Comment by Loic691** [comment]
Test in progress

**Comment by petergridge** [comment]
Hi Just release V2024.10.02 there was another issue affecting the next run. It was not being triggered correctly in the code after a scheduled execution.

**Comment by Loic691** [comment]
Hello Peter
Yes I saw, I done the new update, few minutes ago.
Wating for next runs to test
Thx

**Comment by petergridge** [comment]
Thanks for your help, happy for any issues :) I am pretty sure that issue is fixed now but there is always another on lurking.
