### ISSUE TITLE
Entity not available

### ISSUE THREAD

**Issue by magno-santos** [petergridge/Irrigation-V5#90]
After updating to V2024.09.06/07 I get an entity not available for all the sensor.irrigation-xxxx-status

**Comment by magno-santos** [comment]
![image](https://github.com/user-attachments/assets/fc60d729-288b-4226-9e63-4120b4538726)

**Comment by petergridge** [comment]
Hi,  Can you send me the log details with the errors, this will give me more information. 

I suspect there may be a maximum length for the entity name.

**Comment by petergridge** [comment]
The length does not seem to be the issue:
sensor.morning_afternoon_and_night_twice_a_week_zone_1_next_run is working.

**Comment by magno-santos** [comment]
How can I get these logs?

**Comment by petergridge** [comment]
Go to the settings menu choose system and then  Logs.You should see a screen like this
<img width="651" alt="image" src="https://github.com/user-attachments/assets/525919ac-6c0c-4d95-a6e9-8c9cdcb58c08">
Restart Home assistant and then navigate to the logs to see the error you are getting.

Cheers
Pete

**Comment by magno-santos** [comment]
Deletting and creating again the program seems to solve it

**Comment by petergridge** [comment]
That is great news, I'm not sure why that happens, has it been sometime since you updated the software?
