### ISSUE TITLE
Running multiple zones in parallel

### ISSUE THREAD

**Issue by asafhas** [petergridge/Irrigation-V5#93]
Hello,
I'd like to run 2 zones in parallel under the same program.
Program: Morning (starting at 6:00).
Zone 1 switch: Open for 20 minutes (end at 6:20).
Zone 2 switch: Open for 60 minutes (end at 7:00).
Using "Group" is not good - it makes all switches open and close together.
Using "Zone Delay" with negative value is working, but it's not synchronized with the times of each separate zones. For example, if I want to change Zone-1 to 40 minutes, I'd need to manually change the "Zone Delay" too.

It'd be very helpful to allow running the zones together. Meaning, allow changing the default policy of running them sequential. 
One way to allow it: use same "order" value for both zones, which will tell the program to start them together.

Thank you!

**Comment by petergridge** [comment]
You can set up a similar solution using two programs and unselecting the 'Prevent programs running concurrently' option. 

I will look at adding the feature into the solution. 
![image](https://github.com/user-attachments/assets/00db55cf-46f7-430a-aa4a-406b3b700d3a)

**Comment by asafhas** [comment]
I found a small trick to allow running zones in parallel - remove the 'break' in the first look in 'run_monitor_zones'. But I prefer to stay aligned with the original code, so I will split the Program as you suggested.

By the way - I've noticed a small issue when giving a large minus value for "zone delay". When I used anything larger than the max zone time (-3605 seconds in my example), the Program aborted a second after starting. But the zones kept running.

**Comment by petergridge** [comment]
Hi, 
I have a new version coming out soon, I have added a feature for the degree of parallel running, not sure what to call it. But the idea is you can let 2,3... zones run in parallel, whatever the water pressure will support and as one ends the next one will start to always having the number of zones that match the degree of parallel running

The zone transition capability will be disabled when the degree of parallel is > 1 as the feature becomes meaningless in this context.

I am currently working through the issues with calculating the total run time in this context.

Still a lot of testing to go but this is my last feature to add to the code and I expect the new release will be available late this year or early next.

**Comment by petergridge** [comment]
Hi I have finally release V2024.12.01bo. This is a beta release. Any feedback is welcome

**Comment by asafhas** [comment]
Thank you. I will download the beta release and update here.

**Comment by asafhas** [comment]
I've updated to the Beta version, but found some problems:
- After updating the version, all old programs failed to load. I had to delete them and create new ones from scratch. Received this error:
![image](https://github.com/user-attachments/assets/4f8bbde0-c267-4e60-a234-95b04caea093)
- After creating new program and restarting Home-Assistant, the new program failed to load. Saw this in the logs:
![image](https://github.com/user-attachments/assets/d05b3f4b-c1a8-4ff4-b5be-018ddf73a628)

I did the experiment with one program and one zone.

**Comment by petergridge** [comment]
Thanks, it is possible the upgrade path failed, it may be best to delete and uninstall the component and then reinstall the new version.

- Before you delete the existing installation can you provide me the diagnostic file:
![image](https://github.com/user-attachments/assets/e6e9cb33-7001-459f-bf92-26fb98562ffb)

- Please confirm that the custom component has been completely removed by looking into the config/custom_components directory on you HA device. you should not see an irrigationprogram directory if it has been removed.

**Comment by asafhas** [comment]
Unfortunately, there is no "download diagnostics" option under the 3-dots menu.
However, I was able to find the problem.

On the setup_entry function you use the state of "zone.zone" before that entity is initialized. In my case, it's a switch being initialized by the Tasmota component.
I've added a short waiting loop (1sec x 5 times), and after 1-2 iterations the entity was initialized and the rest of the flow worked OK.

I'll continue to play with the Beta version and let you know if I have more feedbacks.

**Comment by petergridge** [comment]
Thanks, I have added a 5 second 'latency' check into the code. I will release in the next release, so you don't have to mod the code. The latency/timing issues have always been the hardest to find as there is using such varied hardware.

**Comment by asafhas** [comment]
Thank you for taking care of this.

I have some small comments about the UI, which you may want to check:
- Zone watering time is displayed in format HH:MM:SS. It is a bit confusing because Program time is in format HH:MM. I think you can remove the seconds, since it’s not possible to change them anyhow. Also, consider adding “minutes” units to the display.
- When selecting watering-time step > 1 (in advance menu), the slider shows numbers that are not divided by the step. For example, if I choose max time 120 and step 5, the slider will range from 1-116 and show these numbers: 1,6,11,16…
- The “Settings” button in Zone has no label (unlike the button in Program).
- When a zone is running, its name is not turning orange as before. And as the program name is doing.

**Comment by petergridge** [comment]
Thanks for the feedback, 
- the HH:MM:SS format is set by the device class in this case DURATION so I haven't been able to control that.
- I have changed the setting so the minimum value = the step.
- Settings is back
- Icon and colour is back again
I was trying out a new format, but looks like my original is preferred.

I will release a new version soon, but flying tomorrow, maybe do some testing while waiting at the airport 🛩️

**Comment by asafhas** [comment]
I've downloaded version [V2024.12.01b2](https://github.com/petergridge/Irrigation-V5/tree/V2024.12.01b2) and everything works fine.
Thank you for adding the new feature.
You can close the Issue now.
