### ISSUE TITLE
Frequency/Intervals changes for all zones if you update only one

### ISSUE THREAD

**Issue by hanserasmus** [petergridge/Irrigation-V5#94]
First of all, thank you for this project! It seems to be really powerful.

I have a question about frequencies:

I have set up a dropdown helper with a frequency of `1,2,3,4` and `Off`. The idea being that in each zone I can merely select the frequency for that specific zone. However, in a single program with multiple zones, if I change the frequency of a single zone, it changes the frequency of all of them. This seems a bit counter-intuitive. Should it be this way, or is it possibly a bug? My idea was to have a standard interval and then use this interval across multiple cards, for both winter and summer times. But it would seem if I change it on one zone on one card, it changes it **everywhere**. I suspect then the same would be true for runtimes? Meaning that for 4 zones, I would need to create 8 runtime definitions? Again, it seems a bit counterintuitive, because I would rather have a frequency for zone 1 of say 1-15 minutes, in winter it would be 1 minute and summer 10 minutes for example. Meaning if I change one card, it should not affect the other.

Am I missing something in my setup?
Regards

**Comment by petergridge** [comment]
Hi, If you are using the same helper to define frequency on multiple zones they will all inherit the same value, the same will apply for start time. 

My next release, will auto generate the helper objects for the component so users will only need to define the external objects referenced, like rain sensor and zone switch.

**Comment by hanserasmus** [comment]
Thank you for the answer!
