### ISSUE TITLE
Irrigation Inter zone delay bug

### ISSUE THREAD

**Issue by patfelst** [petergridge/Irrigation-V5#96]
Hi there, thanks for this fantastic integration.

I have the Irrigation Inter zone delay set to -5, for 5 seconds overlap in a program. I have 3 zones in one of the programs, and they are all Rainbird valves.

The problem is in this one program, after the first zone runs for say 20 minutes, the next one in teh queue only activates for 5 seconds, then turns off, even though it is also set for 20 minutes. If I set the Inter zone delay to zero, it works ok.

I'd be happy to run without the inter zone delay, just thought I'd let you know.

**Comment by petergridge** [comment]
Thanks for the information, I am working on a big update to the component at the moment, I will check it out for the new release. It is hard for me to test the Rain Bird path I will look at building an emulator component so I can test it I think.

**Comment by patfelst** [comment]
if there's any more info I can give you to help debug, let me know

**Comment by petergridge** [comment]
Looking at the code it appears the Rain Bird controller may not be updating the state of the second switch when they overlap. 

This causes the program to terminate the zone after 5 seconds as it could not determine the state of the switch. A coincidence that your overlap and my checking threshold are the same. You should have an entry in the log indicating a latency issue. It is important that the state of the switch is maintained accurately as the program works by monitoring the 'real' switches to operate.

I remember this is a 'feature' of the Rain Bird product that another user experienced. I am not sure if the state will update after the first zone has completed. If it does a shorted overlap should work if you need it.

If you are willing to look at the code you can go to the custom components directory to find the irrigationprogram component and update the delay value 'CONST_LATENCY' in the const.py file.

**Comment by petergridge** [comment]
I writing persistent notifications in the new version so it should be more obvious when these issues occur.

**Comment by petergridge** [comment]
I found the previous issue

https://github.com/petergridge/Irrigation-V5/issues/56

**Comment by patfelst** [comment]
I've tested it without the inter zone delay for a couple of days and its working fine, so I'll close this.
