### ISSUE TITLE
Link to HACS installation

### ISSUE THREAD

**Issue by MarcFinns** [petergridge/Irrigation-V5#98]
Hi there, I searched HACS and Irrigation V5 does not appear - am i missing something?
Perhaps a link to HACS in the documentation would help... thanks!

**Comment by petergridge** [comment]
Hi,  that's a good point. I never noticed that omission. 
![Screenshot_20241126_121919_Home Assistant.jpg](https://github.com/user-attachments/assets/fb0b3f45-da0b-4e12-bccd-fb0a14a5f64d)

This is the hacs component, I will update the documenting.

**Comment by petergridge** [comment]
Just a note, i am a week or two away from realising a major upgrade. The updated release notes are linked, so you can decide to wait or go ahead with the current version.

**Comment by MarcFinns** [comment]
Hi Peter, thanks for replying! 
Given that there is no shortage of rain, i can definitely wait for the new version... I have a lot to do as i am migrating the whole house from my legacy system. cheers
